<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> 'Türkçeleştirme: <a href="https://phpbbtr.com/">phpBB TR</a>',
	'DIRECTION'		=> 'ltr',
	'DATE_FORMAT'		=> '|d M Y|',		// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'		=> 'tr',

	// You can define different rules for the determination of plural forms here.
	// See https://area51.phpbb.com/docs/dev/3.3.x/language/plurals.html for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 gün',
	'1_MONTH'		=> '1 ay',
	'1_YEAR'		=> '1 yıl',
	'2_WEEKS'		=> '2 hafta',
	'3_MONTHS'		=> '3 ay',
	'6_MONTHS'		=> '6 ay',
	'7_DAYS'		=> '7 gün',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'Hesabınız zaten aktif hale getirildi.',
	'ACCOUNT_DEACTIVATED'			=> 'Hesabınız manuel olarak devre dışı bırakıldı ve yalnızca bir yönetici tarafından yeniden etkinleştirilebilir.',
	'ACP'						=> 'Yönetici Kontrol Paneli',
	'ACP_SHORT'					=> 'YKP',
	'ACTIVE'					=> 'aktif',
	'ACTIVE_ERROR'					=> 'Belirtilen kullanıcı adı şu an aktif değil. Hesabınızı etkinleştirmede sorun yaşıyorsanız lütfen bir mesaj panosu yöneticisiyle iletişime geçin.',
	'ADMINISTRATOR'					=> 'Yönetici',
	'ADMINISTRATORS'				=> 'Yöneticiler',
	'AGE'						=> 'Yaş',
	'AIM'						=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX hatası',
	'AJAX_ERROR_TEXT'				=> 'İsteğiniz işlenirken bir şeyler ters gitti.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'Kullanıcı isteği iptal etti.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'İsteğiniz zaman aşımına uğradı; lütfen tekrar deneyin.',
	'AJAX_ERROR_TEXT_PARSERERROR'		=> 'İstekle ilgili bir şeyler ters gitti ve sunucu geçersiz bir yanıt döndürdü.',
	'ALLOWED'				=> 'İzin verildi',
	'ALL_FILES'				=> 'Tüm dosyalar',
	'ALL_FORUMS'				=> 'Tüm forumlar',
	'ALL_MESSAGES'				=> 'Tüm mesajlar',
	'ALL_POSTS'				=> 'Tüm gönderiler',
	'ALL_TIMES'				=> 'Tüm zamanlar <span title="%2$s">%1$s</span>',
	'ALL_TOPICS'				=> 'Tüm konular',
	'ALT_TEXT'				=> 'Alternatif metin',
	'AND'					=> 've',
	'ARE_WATCHING_FORUM'			=> 'Bu forumdaki yeni gönderilerden haberdar olmak için abone oldunuz.',
	'ARE_WATCHING_TOPIC'			=> 'Bu konudaki yeni mesajlardan haberdar olmak için abone oldunuz.',
	'ASCENDING'				=> 'Artan',
	'ATTACHMENTS'				=> 'Ekler',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'Eklemeye çalıştığınız resim dosyası geçersiz.',
	'AUTHOR'				=> 'Yazar',
	'AUTH_NO_PROFILE_CREATED'		=> 'Kullanıcı profili oluşturma işlemi başarısız oldu.',
	'AUTH_PROVIDER_OAUTH_ERROR_ALREADY_LINKED'			=> 'Bu harici hizmet zaten panodaki başka bir hesapla ilişkilendirilmiş.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'			=> 'Geçersiz veritabanı girişi.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'OAuth hizmet işleyicisine geçersiz hizmet türü belirtildi.',
	'AUTH_PROVIDER_OAUTH_ERROR_REQUEST'				=> 'OAuth isteğiniz işlenirken bir şeyler ters gitti.',
	'AUTH_PROVIDER_OAUTH_RETURN_ERROR'				=> 'Harici hizmet yanlış bir değer döndürdüğü için isteğiniz işlenemiyor.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'OAuth hizmeti oluşturulmadı',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'				=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'				=> 'Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'				=> 'Google',
	'AUTH_PROVIDER_OAUTH_SERVICE_TWITTER'				=> 'Twitter',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'OAuth belirteci depolanmadı.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'		=> 'OAuth belirteci yanlış şekilde depolandı.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'Yüklenen dosya olası bir saldırı vektörü olarak tanımlandığı için yükleme reddedildi.',
	'AVATAR_DISALLOWED_EXTENSION'		=> '<strong>%s</strong> uzantısına izin verilmediğinden bu dosya görüntülenemiyor.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> 'Uzaktaki veriler geçersiz veya bozuk göründüğünden belirtilen avatar yüklenemedi.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'Yüklenen avatar dosyası boş.',
	'AVATAR_INVALID_FILENAME'		=> '%s geçersiz bir dosya adıdır.',
	'AVATAR_NOT_UPLOADED'			=> 'Avatar yüklenemedi.',
	'AVATAR_NO_TEMP_DIR'			=> 'Geçici klasör bulunamadı veya yazılabilir değil.',
	'AVATAR_NO_SIZE'			=> 'Bağlantıdaki avatarın genişliği veya yüksekliği belirlenemedi. Lütfen bunları manuel olarak girin.',
	'AVATAR_NO_UPLOAD_DIR'			=> 'Avatar depolama yolu yok veya yazılabilir değil.',
	'AVATAR_NO_UPLOAD_PATH'			=> 'Avatar yükleme etkin ancak avatar depolama yolu ayarlanmadı.',
	'AVATAR_PARTIAL_UPLOAD'			=> 'Belirtilen dosya yalnızca kısmen yüklendi.',
	'AVATAR_PHP_SIZE_NA'			=> 'Avatarın dosya boyutu çok büyük.<br />Php.ini içinde izin verilen maksimum dosya boyutu belirlenemedi.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'Avatarın dosya boyutu çok büyük. İzin verilen maksimum yükleme boyutu: %1$d %2$s.<br />Lütfen bunun php.ini içinde ayarlandığını ve geçersiz kılınamayacağını unutmayın.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'İstek zaman aşımına uğradığı için belirtilen avatar yüklenemedi.',
	'AVATAR_PHP_UPLOAD_STOPPED'		=> 'Bir PHP uzantısı dosya yüklemeyi durdurdu.',
	'AVATAR_URL_INVALID'			=> 'Belirtilen URL geçersiz.',
	'AVATAR_URL_NOT_FOUND'			=> 'Belirtilen dosya bulunamadı.',
	'AVATAR_WRONG_FILESIZE'			=> 'Avatarın dosya boyutu şu aralıkta olmalıdır: 0 ve %1$d %2$s.',
	'AVATAR_WRONG_SIZE'			=> 'Gönderilen avatar %5$s genişliğinde ve %6$s yüksekliğinde. Avatarlar en azından %1$s genişlik ve %2$s yüksekliğinde olmalı, ama %3$s genişlik ve %4$s yüksekliğinden daha büyük olmamalı.',

	'BACK_TO_TOP'			=> 'Yukarı',
	'BACK_TO_PREV'			=> 'Önceki sayfaya dön',
	'BAN_TRIGGERED_BY_EMAIL'	=> 'Eposta adresinize yasak getirildi.',
	'BAN_TRIGGERED_BY_IP'		=> 'IP adresinize yasak getirildi.',
	'BAN_TRIGGERED_BY_USER'		=> 'Kullanıcı adınıza yasak getirildi.',
	'BBCODE_GUIDE'			=> 'BBCode kılavuzu',
	'BCC'				=> 'BCK',
	'BIRTHDAYS'			=> 'Doğum günleri',
	'BOARD_BAN_PERM'		=> 'Bu panodan <strong>kalıcı olarak</strong> uzaklaştırıldınız.<br /><br />Lütfen daha fazla bilgi için %2$sPano Yöneticisi%3$s ile iletişime geçin.',
	'BOARD_BAN_REASON'		=> 'Uzaklaştırma için belirtilen sebep: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'Şu tarihe kadar bu panodan uzaklaştırıldınız: <strong>%1$s</strong>.<br /><br />Lütfen daha fazla bilgi için %2$sPano Yöneticisi%3$s ile iletişime geçin.',
	'BOARD_DISABLE'			=> 'Üzgünüz ama bu pano şu anda kullanılamıyor.',
	'BOARD_DISABLED'		=> 'Bu pano şu anda hizmet dışı.',
	'BOARD_UNAVAILABLE'		=> 'Üzgünüz pano geçici olarak kullanılamıyor, lütfen birkaç dakika sonra tekrar deneyin.',
	'BROWSING_FORUM'		=> 'Bu forumu görüntüleyen kullanıcılar: %1$s',
	'BROWSING_FORUM_GUESTS'		=> array(
		1	=> 'Bu forumu görüntüleyen kullanıcılar: %2$s ve %1$d misafir',
		2	=> 'Bu forumu görüntüleyen kullanıcılar: %2$s ve %1$d misafir',
	),
	'BUTTON_DELETE'         => 'Sil',
	'BUTTON_EDIT'		=> 'Düzenle',
	'BUTTON_FORUM_LOCKED'	=> 'Kilitli',
	'BUTTON_INFORMATION'    => 'Bilgi',
	'BUTTON_NEW_TOPIC'	=> 'Yeni konu',
	'BUTTON_PM'		=> 'ÖM',
	'BUTTON_PM_FORWARD'	=> 'İlet',
	'BUTTON_PM_NEW'		=> 'Yeni ÖM',
	'BUTTON_PM_REPLY'	=> 'Cevap Gönder',
	'BUTTON_PM_REPLY_ALL'	=> 'Tümünü cevapla',
	'BUTTON_POST_REPLY'	=> 'Cevapla',
	'BUTTON_QUOTE'		=> 'Alıntı',
	'BUTTON_REPORT'         => 'Raporla',
	'BUTTON_TOPIC_LOCKED'	=> 'Kilitli',
	'BUTTON_WARN'           => 'Uyarı',
	'BYTES'			=> 'Byte',
	'BYTES_SHORT'		=> 'B',

	'CANCEL'		=> 'İptal et',
	'CHANGE'		=> 'Değiştir',
	'CHANGE_FONT_SIZE'	=> 'Font boyutunu değiştir',
	'CHANGING_PREFERENCES'	=> 'Pano tercihlerini değiştirme',
	'CHANGING_PROFILE'	=> 'Profil ayarlarını değiştirme',
	'CHARACTERS'		=> array(
		1	=> '%d karakter',
		2	=> '%d karakter',
	),
	// Special version to be used when describing ranges e.g. "min x characters and max y characters"
	'CHARACTERS_XY'			=> array(
		1	=> '%d karakter',
		2	=> '%d karakter',
	),
	'COLLAPSE_VIEW'			=> 'Görünümü daralt',
	'CLOSE_WINDOW'			=> 'Pencereyi kapat',
	'CODE'				=> 'Kod',
	'COLOUR_SWATCH'			=> 'Renk örneği',
	'COLON'				=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'			=> 'Onayla',
	'CONFIRM_CODE'			=> 'Onay kodu',
	'CONFIRM_CODE_EXPLAIN'	=> 'Kodu tam olarak göründüğü gibi girin. Tüm harfler büyük/küçük harfe duyarlı değildir.',
	'CONFIRM_CODE_WRONG'	=> 'Girdiğiniz onay kodu hatalı.',
	'CONFIRM_OPERATION'	=> 'Bu işlemi gerçekleştirmek istediğinize emin misiniz?',
	'CONFIRM_AVATAR_DELETE' => 'Bu avatarı silmek istediğinize emin misiniz?',
	'CONGRATULATIONS'	=> 'Tebrikler',
	'CONNECTION_FAILED'	=> 'Bağlantı başarısız oldu.',
	'CONNECTION_SUCCESS'	=> 'Bağlantı başarılı!',
	'CONTACT'		=> 'İletişim',
	'CONTACT_USER'		=> '%s ile iletişim',
	'CONTACT_US'		=> 'Bize Ulaşın',
	'COOKIE_CONSENT_INFO'	=> 'Daha fazla bilgi edin',
	'COOKIE_CONSENT_MSG'	=> 'Web sitemizde en iyi deneyimi yaşamanızı sağlamak için çerezler kullanılır.',
	'COOKIE_CONSENT_OK'	=> 'Anladım!',
	'COOKIE_CONSENT_HREF'	=> 'http://cookiesandyou.com',
	'COOKIES_DELETED'	=> 'Tüm pano çerezleri başarıyla silindi.',
	'CURRENT_TIME'		=> 'Şu an %s',

	'DAY'				=> 'Gün',
	'DAYS'				=> 'Günler',
	'DELETE'			=> 'Sil',
	'DELETE_ALL'			=> 'Tümünü sil',
	'DELETE_COOKIES'		=> 'Çerezleri sil',
	'DELETE_MARKED'			=> 'İşaretlileri sil',
	'DELETE_POST'			=> 'Mesajı sil',
	'DELIMITER'			=> 'Sınırlayıcı',
	'DESCENDING'			=> 'Azalan',
	'DISABLED'			=> 'Devre dışı',
	'DISPLAY'			=> 'Görüntüle',
	'DISPLAY_GUESTS'		=> 'Misafirleri görüntüle',
	'DISPLAY_MESSAGES'		=> 'Geçmiş mesajları görüntüle',
	'DISPLAY_POSTS'			=> 'Geçmiş mesajları görüntüle',
	'DISPLAY_TOPICS'		=> 'Geçmiş konuları görüntüle',
	'DOMAIN_NO_MX_RECORD_EMAIL'	=> 'Girilen e-posta etki alanında geçerli bir MX kaydı yok.',
	'DOWNLOADED'			=> 'İndirildi',
	'DOWNLOADING_FILE'		=> 'Dosya indiriliyor',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> 'Henüz indirilmedi',
		1	=> '%d kez indirildi',
		2	=> '%d kez indirildi',
	),

	'EDIT_POST'					=>'Mesajı düzenle',
	'ELLIPSIS'					=> '…',
	'EMAIL'						=> 'Eposta', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'					=> 'Eposta adresi',
	'EMAIL_INVALID_EMAIL'				=> 'Girdiğiniz eposta adresi geçersiz.',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> 'Eposta gönderilirken <strong>%1$s satırında</strong> sorunlarla karşılaşıldı. Yanıt: %2$s.',
	'EMPTY_SUBJECT'					=> 'Yeni bir konu açarken başlık belirtmeniz gerekmektedir.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'Yeni bir mesaj yazarken başlık belirtmelisiniz.',
	'ENABLED'					=> 'Etkin',
	'ENCLOSURE'					=> 'Muhafaza',
	'ENTER_USERNAME'				=> 'Kullanıcı adı girin',
	'ERR_CHANGING_DIRECTORY'			=> 'Dizin değiştirilemiyor.',
	'ERR_CONNECTING_SERVER'				=> 'Sunucuya bağlanma hatası.',
	'ERR_JAB_AUTH'					=> 'Jabber sunucusunda yetkilendirme yapılamıyor.',
	'ERR_JAB_CONNECT'				=> 'Jabber sunucusuna bağlanılamadı.',
	'ERR_UNABLE_TO_LOGIN'				=> 'Belirtilen kullanıcı adı veya şifre hatalı.',
	'ERR_UNWATCHING'				=> 'Abonelikten çıkmaya çalışırken bir hata oluştu',
	'ERR_WATCHING'					=> 'Abone olmaya çalışırken bir hata oluştu.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'Belirtilen phpBB yolu geçersiz görünüyor.',
	'ERROR'						=> 'Hata',
	'EXPAND_VIEW'					=> 'Görünümü genişlet',
	'EXTENSION'					=> 'Eklenti',
	'EXTENSION_DISABLED'				=> '<strong>%s</strong> eklentisi etkin değil.',
	'EXTENSION_DISABLED_AFTER_POSTING'		=> '<strong>%s</strong> eklentisi devre dışı bırakıldı ve artık görüntülenemiyor.',
	'EXTENSION_DOES_NOT_EXIST'			=> '<strong>%s</strong> eklentisi mevcut değil.',

	'FACEBOOK'			=> 'Facebook',
	'FAQ'				=> 'SSS',
	'FAQ_EXPLAIN'			=> 'Sıkça Sorulan Sorular',
	'FEATURE_NOT_AVAILABLE' 	=> 'İstenilen özellik bu panoda mevcut değil.',
	'FILENAME'			=> 'Dosya adı',
	'FILESIZE'			=> 'Dosya boyutu',
	'FILEDATE'			=> 'Dosya tarihi',
	'FILE_COMMENT'			=> 'Dosya açıklaması',
	'FILE_CONTENT_ERR'		=> 'Dosyanın içeriği okunamadı: %s',
	'FILE_JSON_DECODE_ERR'		=> 'Json dosyası çözülemedi: %s',
	'FILE_NOT_FOUND'		=> 'İstenilen dosya bulunamadı: %s',
	'FIND_USERNAME'			=> 'Bir üye bul',
	'FOLDER'			=> 'Klasör',
	'FORGOT_PASS'			=> 'Şifremi Unuttum',
	'FORM_INVALID'			=> 'Gönderilen form geçersiz. Tekrar göndermeyi deneyin.',
	'FORUM'				=> 'Forum',
	'FORUMS'			=> 'Forumlar',
	'FORUMS_MARKED'			=> 'Forumlar okundu olarak işaretlendi.',
	'FORUM_CAT'			=> 'Forum kategori',
	'FORUM_INDEX'			=> 'Pano',
	'FORUM_LINK'			=> 'Forum linki',
	'FORUM_LOCATION'		=> 'Forum konumu',
	'FORUM_LOCKED'			=> 'Forum kilitlendi',
	'FORUM_RULES'			=> 'Forum kuralları',
	'FORUM_RULES_LINK'		=> 'Forum kurallarını görmek için lütfen tıklayınız',
	'FROM'				=> '»',
	'FSOCK_DISABLED'		=> 'The operation could not be completed because the <var>fsockopen</var> function has been disabled or the server being queried could not be found.',
	'FSOCK_TIMEOUT'			=> 'Ağ akışından okuma sırasında zaman aşımı oluştu.',

	'FILESYSTEM_CANNOT_CHANGE_FILE_GROUP'		=> 'Unable to change file group',
	'FILESYSTEM_CANNOT_CHANGE_FILE_PERMISSIONS'	=> 'Unable to change file permissions',
	'FILESYSTEM_CANNOT_COPY_FILES'			=> 'Unable to copy files',
	'FILESYSTEM_CANNOT_CREATE_SYMLINK'		=> 'Unable to create a symlink',
	'FILESYSTEM_CANNOT_CREATE_DIRECTORY'		=> 'Unable to create directory',
	'FILESYSTEM_CANNOT_DELETE_FILES'		=> 'Unable to delete files from the system',
	'FILESYSTEM_CANNOT_DUMP_FILE'			=> 'Unable to dump into file',
	'FILESYSTEM_CANNOT_MIRROR_DIRECTORY'		=> 'Unable to mirror directory',
	'FILESYSTEM_CANNOT_RENAME_FILE'			=> 'Unable to rename a file from the system',
	'FILESYSTEM_CANNOT_TOUCH_FILES'			=> 'Unable to create file or change file timestamps',

	'FTP_FSOCK_HOST'		=> 'FTP host',
	'FTP_FSOCK_HOST_EXPLAIN'	=> 'FTP server used to connect your site.',
	'FTP_FSOCK_PASSWORD'		=> 'FTP password',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'Password for your FTP username.',
	'FTP_FSOCK_PORT'		=> 'FTP port',
	'FTP_FSOCK_PORT_EXPLAIN'	=> 'Port used to connect to your server.',
	'FTP_FSOCK_ROOT_PATH'		=> 'Path to phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Path from the root to your phpBB board.',
	'FTP_FSOCK_TIMEOUT'		=> 'FTP timeout',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'	=> 'The amount of time, in seconds, that the system will wait for a reply from your server.',
	'FTP_FSOCK_USERNAME'		=> 'FTP username',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Username used to connect to your server.',

	'FTP_HOST'			=> 'FTP host',
	'FTP_HOST_EXPLAIN'		=> 'FTP server used to connect your site.',
	'FTP_PASSWORD'			=> 'FTP password',
	'FTP_PASSWORD_EXPLAIN'		=> 'Password for your FTP username.',
	'FTP_PORT'			=> 'FTP port',
	'FTP_PORT_EXPLAIN'		=> 'Port used to connect to your server.',
	'FTP_ROOT_PATH'			=> 'Path to phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'Path from the root to your phpBB board.',
	'FTP_TIMEOUT'			=> 'FTP timeout',
	'FTP_TIMEOUT_EXPLAIN'		=> 'The amount of time, in seconds, that the system will wait for a reply from your server.',
	'FTP_USERNAME'			=> 'FTP username',
	'FTP_USERNAME_EXPLAIN'		=> 'Username used to connect to your server.',

	'GENERAL_ERROR'			=> 'Genel hata',
	'GB'				=> 'GB',
	'GIB'				=> 'GiB',
	'GO'				=> 'Git',
	'GOTO_FIRST_POST'		=> 'İlk mesaja git',
	'GOTO_LAST_POST'		=> 'Son mesaja git',
	'GOTO_PAGE'			=> 'Sayfaya git',
	'GROUP'				=> 'Grup',
	'GROUPS'			=> 'Gruplar',
	'GROUP_ERR_TYPE'		=> 'Uygunsuz grup türü belirtildi.',
	'GROUP_ERR_USERNAME'		=> 'Grup adı belirtilmedi.',
	'GROUP_ERR_USER_LONG'		=> 'Grup adları 60 karakteri aşamaz. Belirtilen grup adı çok uzun.',
	'GUEST'				=> 'Misafir',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> '%d misafir çevrimiçi',
		2	=> '%d misafir çevrimiçi',
	),
	'GUEST_USERS_TOTAL'		=> array(
		1	=> '%d misafir',
		2	=> '%d misafir',
	),
	'G_ADMINISTRATORS'		=> 'Yöneticiler',
	'G_BOTS'			=> 'Botlar',
	'G_GUESTS'			=> 'Misafirler',
	'G_REGISTERED'			=> 'Kayıtlı kullanıcılar',
	'G_REGISTERED_COPPA'		=> 'COPPA kayıtlı kullanıcılar',
	'G_GLOBAL_MODERATORS'		=> 'Genel moderatörler',
	'G_NEWLY_REGISTERED'		=> 'Yeni kayıtlı kullanıcılar',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d gizli kullanıcı',
		2	=> '%d gizli kullanıcı',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d gizli',
		2	=> '%d gizli',
	),
	'HIDE_GUESTS'			=> 'Misafirleri gizle',
	'HIDE_ME'			=> 'Bu oturumda çevrimiçi durumumu gizle',
	'HOURS'				=> 'Saat',
	'HOME'				=> 'Ana sayfa',

	'ICQ'				=> 'ICQ',
	'IF'				=> 'Eğer',
	'IMAGE'				=> 'Resim',
	'IMAGE_FILETYPE_INVALID'	=> 'Image file type %d for mimetype %s not supported.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Image file type mismatch: expected extension %1$s but extension %2$s given.',
	'IN'				=> '',
	'INACTIVE'			=> 'Etkin değil',
	'INDEX'				=> 'Index page',
	'INFORMATION'			=> 'Bilgi',
	'INSECURE_REDIRECT'		=> 'Potansiyel olarak güvenli olmayan URLye yönlendirilmeye çalışıldı.',
	'INTERESTS'			=> 'İlgi alanları',
	'INVALID_DIGEST_CHALLENGE'	=> 'Invalid digest challenge.',
	'INVALID_EMAIL_LOG'		=> '<strong>%s</strong> possibly an invalid email address?',
	'INVALID_FEED_ATTACHMENTS'	=> 'The selected feed tried fetching attachments with invalid constraints.',
	'INVALID_PLURAL_RULE'		=> 'The chosen plural rule is invalid. Valid values are integers between 0 and 15.',
	'IP'				=> 'IP',
	'IP_BLACKLISTED'		=> 'Your IP %1$s has been blocked because it is blacklisted. For details please see <a href="%2$s">%2$s</a>.',

	'JABBER'			=> 'Jabber',
	'JOINED'			=> 'Katıldı',
	'JUMP_PAGE'			=> 'Gitmek istediğiniz sayfa numarasını giriniz',
	'JUMP_TO'			=> 'Geçiş yap',
	'JUMP_TO_PAGE'			=> 'Sayfaya geç',
	'JUMP_TO_PAGE_CLICK'		=> 'Sayfaya geçmek için tıklayın…',

	'KB'				=> 'KB',
	'KIB'				=> 'KiB',

	'LAST_POST'			=> 'Son mesaj',
	'LAST_UPDATED'			=> 'Son güncelleme',
	'LAST_VISIT'			=> 'Son ziyaret',
	'LDAP_NO_LDAP_EXTENSION'	=> 'LDAP extension not available.',
	'LDAP_NO_SERVER_CONNECTION'	=> 'Could not connect to LDAP server.',
	'LDAP_SEARCH_FAILED'		=> 'An error occurred while searching the LDAP directory.',
	'LEGEND'			=> 'Yetki düzeni',
	'LIVE_SEARCHES_NOT_ALLOWED'	=> 'Canlı aramalara izin verilmiyor',
	'LOADING'			=> 'Yükleniyor',
	'LOCATION'			=> 'Konum',
	'LOCK_POST'			=> 'Mesajı kilitle',
	'LOCK_POST_EXPLAIN'		=> 'Düzenlemeyi engelle',
	'LOCK_TOPIC'			=> 'Konuyu kilitle',
	'LOGIN'				=> 'Giriş',
	'LOGIN_CHECK_PM'		=> 'Özel mesajlarınızı kontrol etmek için giriş yapın.',
	'LOGIN_CONFIRMATION'				=> 'Giriş onayı',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'To prevent brute forcing accounts the board requires you to enter a confirmation code after a maximum amount of failed logins. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to pass the CAPTCHA test.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'		=> 'You have not been authenticated by Apache.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'A non-existent OAuth service has been requested.',
	'LOGIN_ERROR_PASSWORD'				=> 'You have specified an incorrect password. Please check your password and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'			=> 'It was not possible to convert your password when updating this bulletin board’s software. Please %srequest a new password%s. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_USERNAME'				=> 'You have specified an incorrect username. Please check your username and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_FORUM'					=> 'To view or post in this forum you must enter its password.',
	'LOGIN_INFO'					=> 'In order to login you must be registered. Registering takes only a few moments but gives you increased capabilities. The board administrator may also grant additional permissions to registered users. Before you register please ensure you are familiar with our terms of use and related policies. Please ensure you read any forum rules as you navigate around the board.',
	'LOGIN_VIEWFORUM'				=> 'The board requires you to be registered and logged in to view this forum.',
	'LOGIN_EXPLAIN_EDIT'				=> 'In order to edit posts in this forum you have to be registered and logged in.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'In order to view the online list you have to be registered and logged in.',
	'LOGIN_REQUIRED'				=> 'Bu işlemi gerçekleştirmek için giriş yapmanız gerekmektedir.',
	'LOGOUT'					=> 'Çıkış',
	'LOGOUT_USER'					=> 'Çıkış [ %s ]',
	'LOG_ME_IN'					=> 'Beni hatırla',

	'MAIN'			=> 'Ana',
	'MARK'			=> 'İşaretle',
	'MARK_ALL'		=> 'Tümünü işaretle',
	'MARK_ALL_READ'		=> 'Tümünü okundu işaretle',
	'MARK_FORUMS_READ'	=> 'Forumları okundu olarak işaretle',
	'MARK_READ'		=> 'Okundu olarak işaretle',
	'MARK_SUBFORUMS_READ'	=> 'Alt forumları okundu olarak işaretle',
	'MB'			=> 'MB',
	'MIB'			=> 'MiB',
	'MCP'			=> 'Moderatör Kontrol Paneli',
	'MCP_SHORT'		=> 'MCP',
	'MEMBERLIST'		=> 'Üyeler',
	'MEMBERLIST_EXPLAIN'	=> 'Üyelerin tam listesini görüntüle',
	'MERGE'			=> 'Birleştir',
	'MERGE_POSTS'		=> 'Mesajları taşı',
	'MERGE_TOPIC'		=> 'Konu birleştir',
	'MESSAGE'		=> 'Mesaj',
	'MESSAGES'		=> 'Mesajlar',
	'MESSAGES_COUNT'	=> array(
		0	=> 'sınırsız mesaj',
		1	=> '%d mesaj',
		2	=> '%d mesaj',
	),
	'MESSAGE_BODY'			=> 'Mesaj gövdesi',
	'MINUTES'			=> 'Dakika',
	'MODERATE'			=> 'Moderasyon',
	'MODERATOR'			=> 'Moderatör',
	'MODERATORS'			=> 'Moderatörler',
	'MODULE_NOT_ACCESS'		=> 'Modül erişilebilir değil',
	'MODULE_NOT_FIND'		=> '%s modülü bulunamıyor',
	'MODULE_FILE_INCORRECT_CLASS'	=> 'Module file %s does not contain correct class [%s]',
	'MONTH'				=> 'Ay',
	'MOVE'				=> 'Taşı',

	'NA'				=> 'N/A',
	'NEWEST_USER'			=> 'En yeni üyemiz <strong>%s</strong>',
	'NEW_MESSAGE'			=> 'Yeni mesaj',
	'NEW_MESSAGES'			=> 'Yeni mesajlar',
	'NEW_POST'			=> 'Yeni mesaj',	// Not used anymore
	'NEW_POSTS'			=> 'Yeni mesajlar',	// Not used anymore
	'NEXT'				=> 'Sonraki',	// Used in pagination
	'NEXT_STEP'			=> 'Sonra',
	'NEVER'				=> 'Hiç',
	'NO'				=> 'Hayır',
	'NO_NOTIFICATIONS'		=> 'Hiçbir bildiriminiz yok',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'Bu grubu yönetme izniniz yok.',
	'NOT_AUTHORISED'		=> 'Bu alana erişim yetkiniz yok.',
	'NOT_WATCHING_FORUM'		=> 'Bu forumdaki güncellemelere artık abone değilsiniz.',
	'NOT_WATCHING_TOPIC'		=> 'Artık bu konuya abone değilsiniz.',
	'NOTIFICATIONS'			=> 'Bildirimler',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '<strong>Reply</strong> from %1$s in bookmarked topic:',
	),
	'NOTIFICATION_FORUM'			=> '<em>Forum:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '<strong>Group request</strong> from %1$s to join the group %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>Group request approved</strong> to join the group %1$s.',
	'NOTIFICATION_METHOD_INVALID'		=> 'The method "%s" does not refer to a valid notification method.',
	'NOTIFICATION_PM'			=> '<strong>Private Message</strong> from %1$s:',
	'NOTIFICATION_POST'			=> array(
		1	=> '<strong>Reply</strong> from %1$s in topic:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>Mesaj onaylandı</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>Mesaj reddedildi</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>Mesaj onayı</strong> talebi » %1$s:',
	'NOTIFICATION_QUOTE'			=> array(
		1	=> '%1$s tarafından <strong>alıntı yapıldı</strong>:',
	),
	'NOTIFICATION_REFERENCE'		=> '"%1$s"',
	'NOTIFICATION_REASON'			=> '<em>Sebep:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'		=> '<strong>Özel Mesaj raporlandı</strong> » %1$s:',
	'NOTIFICATION_REPORT_PM_CLOSED'		=> '<strong>Private Message report closed</strong> » %1$s:',
	'NOTIFICATION_REPORT_POST'		=> '<strong>Mesaj raporlandı</strong> » %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Rapor kapatıldı</strong> » %1$s for:',
	'NOTIFICATION_TOPIC'			=> '<strong>Yeni konu</strong> » %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>Konu onaylandı</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>Konu reddedildi</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>Konu onayı</strong> talebi » %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'The notification type "%s" is missing from the file system.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> 'Devre dışı bırakılmış veya yeni kayıtlı kullanıcı için <strong>aktivasyon gerekiyor</strong>: “%1$s”',
	// Used in conjunction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'		=> 'diğerleri',
	'NOTIFICATION_X_OTHERS'			=> array(
		2	=> '%d diğer',
	),
	'NOTIFY_ADMIN'			=> 'Please notify the board administrator or webmaster.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Please notify the board administrator or webmaster: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'You are not allowed to access this file.',
	'NO_ACTION'			=> 'No action specified.',
	'NO_ADMINISTRATORS'		=> 'Hiçbir yönetici yok.',
	'NO_AUTH_ADMIN'			=> 'Access to the Administration Control Panel is not allowed as you do not have administrative permissions.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'You are not able to re-authenticate as a different user.',
	'NO_AUTH_OPERATION'		=> 'You do not have the necessary permissions to complete this operation.',
	'NO_AVATARS'			=> 'No avatars currently available',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Could not connect to smtp host : %1$s : %2$s',
	'NO_BIRTHDAYS'			=> 'Bugün doğum günü yok',
	'NO_EMAIL_MESSAGE'		=> 'Email message was blank.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Could not get mail server response codes.',
	'NO_EMAIL_SUBJECT'		=> 'No email subject specified.',
	'NO_FORUM'			=> 'The forum you selected does not exist.',
	'NO_FORUMS'			=> 'Bu panonun forumu yok.',
	'NO_GROUP'			=> 'The requested usergroup does not exist.',
	'NO_GROUP_MEMBERS'		=> 'This group currently has no members.',
	'NO_IPS_DEFINED'		=> 'No IP addresses or hostnames defined',
	'NO_MEMBERS'			=> 'No members found for this search criterion.',
	'NO_MESSAGES'			=> 'Mesaj yok',
	'NO_MODE'			=> 'No mode specified.',
	'NO_MODERATORS'			=> 'Moderatör yok.',
	'NO_NEW_MESSAGES'		=> 'Yeni mesaj yok',
	'NO_NEW_POSTS'			=> 'Yeni mesaj yok',	// Not used anymore
	'NO_ONLINE_USERS'		=> 'Kayıtlı kullanıcı yok',
	'NO_POSTS'			=> 'Mesaj yok',
	'NO_POSTS_TIME_FRAME'		=> 'No posts exist inside this topic for the selected time frame.',
	'NO_FEED_ENABLED'		=> 'Feeds are not available on this board.',
	'NO_FEED'			=> 'The requested feed is not available.',
	'NO_STYLE_DATA'			=> 'Could not get style data for user_style %s and set for user_id %s',
	'NO_STYLE_CFG'			=> 'Could not get the style configuration file for: %s',
	'NO_SUBJECT'			=> 'No subject specified',	// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'The specified search backend doesn’t exist.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'No supported authentication methods.',
	'NO_TOPIC'			=> 'The requested topic does not exist.',
	'NO_TOPIC_FORUM'		=> 'The topic or forum no longer exists.',
	'NO_TOPICS'			=> 'There are no topics or posts in this forum.',
	'NO_TOPICS_TIME_FRAME'		=> 'No topics exist inside this forum for the selected time frame.',
	'NO_UNREAD_POSTS'		=> 'Okunmamış mesaj yok',
	'NO_UPLOAD_FORM_FOUND'		=> 'Upload initiated but no valid file upload form found.',
	'NO_USER'			=> 'The requested user does not exist.',
	'NO_USERS'			=> 'The requested users do not exist.',
	'NO_USER_SPECIFIED'		=> 'No username was specified.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d ek',
		2	=> '%d ek',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'No posts in queue',		// 0
		1			=> '1 post in queue',		// 1
		2			=> '%d posts in queue',		// 2+
	),

	'OCCUPATION'			=> 'Occupation',
	'OFFLINE'			=> 'Çevrimdışı',
	'ONLINE'			=> 'Çevrimiçi',
	'ONLINE_BUDDIES'		=> 'Çevrimiçi arkadaşlar',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'Toplamda <strong>%1$d</strong> kullanıcı çevrimiçi :: %2$s ve %3$s',
		2	=> 'Toplamda <strong>%1$d</strong> kullanıcı çevrimiçi :: %2$s ve %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'Toplamda <strong>%1$d</strong> kullanıcı çevrimiçi :: %2$s, %3$s ve %4$s',
		2	=> 'Toplamda <strong>%1$d</strong> kullanıcı çevrimiçi :: %2$s, %3$s ve %4$s',
	),
	'OPTIONS'			=> 'Seçenekler',

	'PAGE_NOT_FOUND'		=> 'İstenilen sayfa bulunamadı.',
	'PAGE_OF'			=> '<strong>%2$d</strong> sayfa içinde <strong>%1$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'Sayfa %s',
	'PASSWORD'			=> 'Şifre',
	'PIXEL'				=> 'px',
	'PIXELS'			=> array(
		1	=> '%d pixel',
		2	=> '%d pixels',
	),
	'PLEASE_WAIT'			=> 'Lütfen bekleyin.',
	'PM'				=> 'ÖM',
	'PM_REPORTED'			=> 'Raporu görüntülemek için tıklayın',
	'POSTING_MESSAGE'		=> '%s konusunda mesaj yazıyor',
	'POSTING_PRIVATE_MESSAGE'	=> 'Özel mesaj yazıyor',
	'POST'				=> 'Mesaj',
	'POST_ANNOUNCEMENT'		=> 'Duyuru',
	'POST_STICKY'			=> 'Sabit',
	'POSTED'			=> 'Yazıldı',
	'POSTED_IN_FORUM'		=> '»',
	'POSTED_ON_DATE'		=> '»',
	'POSTS'				=> 'Mesaj',
	'POSTS_UNAPPROVED'		=> 'Bu konudaki en az bir mesaj onaylanmadı.',
	'POSTS_UNAPPROVED_FORUM'	=> 'Bu forumdaki en az bir gönderi onaylanmadı.',
	'POST_BY_AUTHOR'		=> '',
	'POST_BY_FOE'			=> 'Bu mesajı şu anda engelliler listenizde bulunan <strong>%1$s</strong> gönderdi.',
	'POST_DISPLAY'			=> 'Bu mesajı görüntüle',
	'POST_DAY'			=> '%.2f mesaj hergün için',
	'POST_DELETED_ACTION'		=> 'Silinen mesaj:',
	'POST_DELETED'			=> 'Bu mesaj silindi.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s.',
	'POST_DELETED_BY_REASON'	=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s for the following reason: %4$s',
	'POST_DETAILS'			=> 'Mesaj ayrıntıları',
	'POST_NEW_TOPIC'		=> 'Yeni konu aç',
	'POST_PCT'			=> '%.2f%% of all posts',
	'POST_PCT_ACTIVE'		=> '%.2f%% of user’s posts',
	'POST_PCT_ACTIVE_OWN'		=> '%.2f%% of your posts',
	'POST_REPLY'			=> 'Cevap yaz',
	'POST_REPORTED'			=> 'Raporu görüntülemek için tıkla',
	'POST_SUBJECT'			=> 'Mesaj başlığı',
	'POST_TIME'			=> 'Mesaj zamanı',
	'POST_TOPIC'			=> 'Yeni bir konu aç',
	'POST_UNAPPROVED_ACTION'	=> 'Onay bekleyen mesaj:',
	'POST_UNAPPROVED'		=> 'Bu mesaj onaylanmadı.',
	'POST_UNAPPROVED_EXPLAIN'	=> 'Bu gönderi bir moderatör tarafından onaylanana kadar diğer kullanıcılar tarafından görülemez.',
	'POWERED_BY'			=> 'Powered by %s',

	'QUOTE'				=> 'Alıntı',

	'PREVIEW'			=> 'Ön izleme',
	'PREVIOUS'			=> 'Önce',	// Used in pagination
	'PREVIOUS_STEP'			=> 'Önce',
	'PRIVACY'			=> 'Gizlilik politikası',
	'PRIVACY_LINK'			=> 'Gizlilik',
	'PRIVATE_MESSAGE'		=> 'Özel mesaj',
	'PRIVATE_MESSAGES'		=> 'Özel mesajlar',
	'PRIVATE_MESSAGING'		=> 'Özel mesajlaşma',
	'PROFILE'			=> 'Kullanıcı kontrol Paneli',

	'QUICK_LINKS'			=> 'Hızlı Linkler',

	'RANK'				=> 'Rütbe',
	'READING_FORUM'			=> '%s içinde konular görüntülüyor',
	'READING_GLOBAL_ANNOUNCE'	=> 'Genel duyuru okuyor',
	'READING_LINK'			=> 'Following forum link %s',
	'READING_TOPIC'			=> '%s konusunu okuyor',
	'READ_PROFILE'			=> 'Profil',
	'REASON'			=> 'Sebep',
	'RECORD_ONLINE_USERS'		=> 'Şimdiye kadar en çok çevrimiçi %2$s tarihinde <strong>%1$s</strong> kullanıcı',
	'REDIRECT'			=> 'Yönlendirme',
	'REDIRECTS'			=> 'Toplam yönlendirme',
	'REGISTER'			=> 'Kayıt',
	'REGISTERED_USERS'		=> 'Kayıtlı kullanıcılar:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'		=> array(
		1	=> '%1$d kayıtlı kullanıcı ve %2$s çevrimiçi',
		2	=> '%1$d kayıtlı kullanıcı ve %2$s çevrimiçi',
	),
	'REG_USERS_TOTAL'		=> array(
		1	=> '%d kayıtlı',
		2	=> '%d kayıtlı',
	),
	'REMOVE'			=> 'Kaldır',
	'REMOVE_INSTALL'		=> 'Lütfen panonuzu kullanmadan önce kurulum dizinini silin, taşıyın veya yeniden adlandırın. Bu dizin hala mevcutsa yalnızca Yönetim Kontrol Panelinden (YKP) erişilebilir.',
	'REPLIES'			=> 'Cevaplar',
	'REPLY_WITH_QUOTE'		=> 'Alıntıyla cevapla',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Genel duyuruya cevap yazıyor',
	'REPLYING_MESSAGE'		=> '%s konusuna cevap yazıyor',
	'REPORT_BY'			=> 'Raporlayan',
	'REPORT_POST'			=> 'Mesajı raporla',
	'REPORTING_POST'		=> 'Reporting post',
	'RESEND_ACTIVATION'		=> 'Aktivasyon epostasını tekrar gönder',
	'RESET'				=> 'Sıfırla',
	'RESTORE_PERMISSIONS'		=> 'İzinleri geri yükle',
	'RETURN_INDEX'			=> '%sAna sayfaya dön%s',
	'RETURN_FORUM'			=> '%sReturn to the forum last visited%s',
	'RETURN_PAGE'			=> '%sÖnceki sayfaya dön%s',
	'RETURN_TOPIC'			=> '%sSon ziyaret edilen konuya dön%s',
	'RETURN_TO'			=> 'Return to “%s”',
	'RETURN_TO_INDEX'		=> 'Ana sayfaya dön',

	'ROUTE_NOT_FOUND'		=> 'The requested route “%s” could not be found.',
	'ROUTE_INVALID_MISSING_PARAMS'	=> 'Invalid or missing parameters passed for route “%s”.',

	'FEED'				=> 'Feed',
	'FEED_NEWS'			=> 'News',
	'FEED_TOPICS_ACTIVE'		=> 'Aktif konular',
	'FEED_TOPICS_NEW'		=> 'Yeni konular',
	'RULES_ATTACH_CAN'		=> 'You <strong>can</strong> post attachments in this forum',
	'RULES_ATTACH_CANNOT'		=> 'You <strong>cannot</strong> post attachments in this forum',
	'RULES_DELETE_CAN'		=> 'You <strong>can</strong> delete your posts in this forum',
	'RULES_DELETE_CANNOT'		=> 'You <strong>cannot</strong> delete your posts in this forum',
	'RULES_DOWNLOAD_CAN'		=> 'You <strong>can</strong> download attachments in this forum',
	'RULES_DOWNLOAD_CANNOT'		=> 'You <strong>cannot</strong> download attachments in this forum',
	'RULES_EDIT_CAN'		=> 'You <strong>can</strong> edit your posts in this forum',
	'RULES_EDIT_CANNOT'		=> 'You <strong>cannot</strong> edit your posts in this forum',
	'RULES_LOCK_CAN'		=> 'You <strong>can</strong> lock your topics in this forum',
	'RULES_LOCK_CANNOT'		=> 'You <strong>cannot</strong> lock your topics in this forum',
	'RULES_POST_CAN'		=> 'You <strong>can</strong> post new topics in this forum',
	'RULES_POST_CANNOT'		=> 'You <strong>cannot</strong> post new topics in this forum',
	'RULES_REPLY_CAN'		=> 'You <strong>can</strong> reply to topics in this forum',
	'RULES_REPLY_CANNOT'		=> 'You <strong>cannot</strong> reply to topics in this forum',
	'RULES_VOTE_CAN'		=> 'You <strong>can</strong> vote in polls in this forum',
	'RULES_VOTE_CANNOT'		=> 'You <strong>cannot</strong> vote in polls in this forum',

	'SEARCH'			=> 'Arama',
	'SEARCH_MINI'			=> 'Arama…',
	'SEARCH_ADV'			=> 'Gelişmiş arama',
	'SEARCH_ADV_EXPLAIN'		=> 'Gelişmiş arama seçeneklerini görüntüle',
	'SEARCH_KEYWORDS'		=> 'Anahtar kelimeler ara',
	'SEARCHING_FORUMS'		=> 'Forumlarda ara',
	'SEARCH_ACTIVE_TOPICS'		=> 'Aktif konular',
	'SEARCH_FOR'			=> 'Search for',
	'SEARCH_FORUM'			=> 'Bu forumda ara…',
	'SEARCH_NEW'			=> 'Yeni mesajlar',
	'SEARCH_POSTS_BY'		=> 'Search posts by',
	'SEARCH_SELF'			=> 'Senin mesajların',
	'SEARCH_TOPIC'			=> 'Bu konuda ara…',
	'SEARCH_UNANSWERED'		=> 'Cevapsız konular',
	'SEARCH_UNREAD'			=> 'Okunmamış mesajlar',
	'SEARCH_USER_POSTS'		=> 'Kullanıcının mesajlarını ara',
	'SECONDS'			=> 'Saniye',
	'SEE_ALL'			=> 'Hepsini gör',
	'SELECT'			=> 'Seç',
	'SELECT_ALL_CODE'		=> 'Tümünü seç',
	'SELECT_DESTINATION_FORUM'	=> 'Lütfen bir hedef forum seçin',
	'SELECT_FORUM'			=> 'Bir forum seç',
	'SEND_EMAIL'			=> 'Eposta gönder',	// Used for submit buttons
	'SEND_EMAIL_USER'		=> '%s kullanıcısına eposta gönder',
	'SEND_PRIVATE_MESSAGE'		=> 'Özel mesaj gönder',
	'SETTINGS'			=> 'Ayarlar',
	'SIGNATURE'			=> 'İmzca',
	'SKIP'				=> 'İçeriği geç',
	'SKYPE'				=> 'Skype',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP server does not support authentication.',
	'SORRY_AUTH_READ'		=> 'You are not authorised to read this forum.',
	'SORRY_AUTH_READ_TOPIC'		=> 'You are not authorised to read this topic.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'You are not authorised to download this attachment.',
	'SORT_BY'			=> 'Sort by',
	'SORT_DIRECTION'		=> 'Direction',
	'SORT_JOINED'			=> 'Joined date',
	'SORT_LOCATION'			=> 'Location',
	'SORT_OPTIONS'			=> 'Display and sorting options',
	'SORT_RANK'			=> 'Rank',
	'SORT_POSTS'			=> 'Posts',
	'SORT_TOPIC_TITLE'		=> 'Konu başlığı',
	'SORT_USERNAME'			=> 'Kullanıcı adı',
	'SPLIT_TOPIC'			=> 'Konuyu böl',
	'SQL_ERROR_OCCURRED'		=> 'An SQL error occurred while fetching this page. Please contact the %sBoard Administrator%s if this problem persists.',
	'STATISTICS'			=> 'İstatistikler',
	'START_WATCHING_FORUM'		=> 'Foruma abone ol',
	'START_WATCHING_TOPIC'		=> 'Konuya abone ol',
	'STOP_WATCHING_FORUM'		=> 'Forum aboneliğinden çık',
	'STOP_WATCHING_TOPIC'		=> 'Konu aboneliğinden çık',
	'STRING_LIST_MULTI'		=> '%1$s, and %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s and %2$s',
	'SUBFORUM'			=> 'Alt forum',
	'SUBFORUMS'			=> 'Alt forumlar',
	'SUBJECT'			=> 'Başlık',
	'SUBMIT'			=> 'Gönder',

	'TB'				=> 'TB',
	'TERMS_LINK'			=> 'Koşullar',
	'TERMS_USE'			=> 'Kullanım koşulları',
	'TEST_CONNECTION'		=> 'Test bağlantısı',
	'THE_TEAM'			=> 'Ekip',
	'TIB'				=> 'TiB',
	'TIME'				=> 'Time',
	'TIMEOUT_PROCESSING_REQ'	=> 'İstek zaman aşımına uğradı.',

	'TOO_LARGE'				=> 'The value you entered is too large.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'The value of <strong>Maximum number of allowed recipients per private message</strong> setting you entered is too large.',

	'TOO_LONG'				=> 'The value you entered is too long.',

	'TOO_LONG_CONFIRM_CODE'			=> 'The confirm code you entered is too long.',
	'TOO_LONG_DATEFORMAT'			=> 'The date format you entered is too long.',
	'TOO_LONG_JABBER'			=> 'The Jabber account name you entered is too long.',
	'TOO_LONG_NEW_PASSWORD'			=> 'The password you entered is too long.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'The password confirmation you entered is too long.',
	'TOO_LONG_USER_PASSWORD'		=> 'The password you entered is too long.',
	'TOO_LONG_USERNAME'			=> 'The username you entered is too long.',
	'TOO_LONG_EMAIL'			=> 'The email address you entered is too long.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'You have tried to vote for too many options.',

	'TOO_SHORT'				=> 'The value you entered is too short.',

	'TOO_SHORT_CONFIRM_CODE'		=> 'The confirm code you entered is too short.',
	'TOO_SHORT_DATEFORMAT'			=> 'The date format you entered is too short.',
	'TOO_SHORT_JABBER'			=> 'The Jabber account name you entered is too short.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'The password you entered is too short.',
	'TOO_SHORT_PASSWORD_CONFIRM'		=> 'The password confirmation you entered is too short.',
	'TOO_SHORT_USER_PASSWORD'		=> 'The password you entered is too short.',
	'TOO_SHORT_USERNAME'			=> 'The username you entered is too short.',
	'TOO_SHORT_EMAIL'			=> 'The email address you entered is too short.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'The email address confirmation you entered is too short.',
	'TOO_SMALL'				=> 'The value you entered is too small.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'The value of <strong>Maximum number of allowed recipients per private message</strong> setting you entered is too small.',

	'TOPIC'				=> 'Konu',
	'TOPICS'			=> 'Konular',
	'TOPICS_UNAPPROVED'		=> 'At least one topic in this forum has not been approved.',
	'TOPIC_ICON'			=> 'Konu ikonu',
	'TOPIC_LOCKED'			=> 'This topic is locked, you cannot edit posts or make further replies.',
	'TOPIC_LOCKED_SHORT'		=> 'Konu kilitli',
	'TOPIC_MOVED'			=> 'Konu taşındı',
	'TOPIC_REVIEW'			=> 'Topic review',
	'TOPIC_TITLE'			=> 'Konu başlığı',
	'TOPIC_UNAPPROVED'		=> 'Bu konu onaylanmadı.',
	'TOPIC_UNAPPROVED_FORUM'	=> array(
		1	=> 'Onay bekleyen konu',
		2	=> 'Onay bekleyen konular',
	),
	'TOPIC_DELETED'		=> 'Bu konu silindi.',
	'TOTAL_ATTACHMENTS'	=> 'Ek(ler)',
	'TOTAL_LOGS'		=> array(
		1	=> '%d kayıt',
		2	=> '%d kayıt',
	),
	'TOTAL_PMS'		=> array(
		1	=> 'Toplamda %d özel mesaj',
		2	=> 'Toplamda %d özel mesaj',
	),
	'TOPIC_POLL'		=> 'Bu konunun bir anketi var.',
	'TOTAL_POSTS'		=> 'Toplam mesaj',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> 'Toplam mesaj <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> 'Bu konu raporlandı',
	'TOTAL_TOPICS'		=> array(
		2	=> 'Toplam konu <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> 'Toplam üye <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> 'Takip edilen PHP hataları: %s',
	'TWITTER'		=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'		=> 'It was not possible to determine the dimensions of the image. Please verify that the URL you entered is correct.',
	'UNABLE_TO_DELIVER_FILE'	=> 'Unable to deliver file.',
	'UNKNOWN_BROWSER'		=> 'Bilinmeyen tarayıcı',
	'UNMARK_ALL'			=> 'Tümünün işaretini kaldır',
	'UNREAD_MESSAGES'		=> 'Okunmamış mesajlar',
	'UNREAD_POST'			=> 'Okunmamış mesaj',
	'UNREAD_POSTS'			=> 'Okunmamış mesajlar',
	'UNWATCH_FORUM_CONFIRM'		=> 'Are you sure you wish to unsubscribe from this forum?',
	'UNWATCH_FORUM_DETAILED'	=> 'Are you sure you wish to unsubscribe from the forum “%s”?',
	'UNWATCH_TOPIC_CONFIRM'		=> 'Are you sure you wish to unsubscribe from this topic?',
	'UNWATCH_TOPIC_DETAILED'	=> 'Are you sure you wish to unsubscribe from the topic “%s”?',
	'UNWATCHED_FORUMS'		=> 'You are no longer subscribed to the selected forums.',
	'UNWATCHED_TOPICS'		=> 'You are no longer subscribed to the selected topics.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'You are no longer subscribed to the selected entries.',
	'UPDATE'			=> 'Update',
	'UPLOAD_IN_PROGRESS'		=> 'The upload is currently in progress.',
	'URL_REDIRECT'			=> 'If your browser does not support meta redirection %splease click HERE to be redirected%s.',
	'USERGROUPS'			=> 'Gruplar',
	'USERNAME'			=> 'Kullanıcı adı',
	'USERNAMES'			=> 'Kullanıcı adları',
	'USER_AVATAR'			=> 'Kullanıcı avatarı',
	'USER_CANNOT_READ'		=> 'Bu forumdaki mesajları okuyamazsınız.',
	'USER_POSTS'			=> array(
		1	=> '%d Mesaj',
		2	=> '%d Mesaj',
	),
	'USERS'				=> 'Kullanıcılar',
	'USE_PERMISSIONS'		=> 'Kullanıcının izinlerini test et',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'We are sorry, but you are not authorised to use this feature. You may have just registered here and may need to participate more in discussions to be able to use this feature.',

	'VARIANT_DATE_SEPARATOR'		=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'				=> 'Görüntülendi',
	'VIEWED_COUNTS'		=> array(
		0	=> 'Hiç görüntülenmedi',
		1	=> '%d kez görüntülendi',
		2	=> '%d kez görüntülendi',
	),
	'VIEWING_CONTACT_ADMIN'		=> 'Viewing contact page',
	'VIEWING_FAQ'			=> 'Viewing FAQ',
	'VIEWING_MEMBERS'		=> 'Viewing member details',
	'VIEWING_ONLINE'		=> 'Viewing who is online',
	'VIEWING_MCP'			=> 'Viewing moderator control panel',
	'VIEWING_MEMBER_PROFILE'	=> 'Viewing member profile',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Viewing private messages',
	'VIEWING_REGISTER'		=> 'Registering account',
	'VIEWING_UCP'			=> 'Viewing user control panel',
	'VIEWS'				=> 'Views',
	'VIEW_BOOKMARKS'		=> 'View bookmarks',
	'VIEW_FORUM_LOGS'		=> 'View Logs',
	'VIEW_LATEST_POST'		=> 'View the latest post',
	'VIEW_NEWEST_POST'		=> 'View first unread post',
	'VIEW_NOTES'			=> 'View user notes',
	'VIEW_ONLINE_TIMES'		=> array(
		1	=> 'based on users active over the past %d minute',
		2	=> 'based on users active over the past %d minutes',
	),
	'VIEW_TOPIC'			=> 'View topic',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Duyuru: ',
	'VIEW_TOPIC_GLOBAL'		=> 'Genel Duyuru: ',
	'VIEW_TOPIC_LOCKED'		=> 'Kilitli: ',
	'VIEW_TOPIC_LOGS'		=> 'Kayıtları görüntüle',
	'VIEW_TOPIC_MOVED'		=> 'Taşındı: ',
	'VIEW_TOPIC_POLL'		=> 'Anket: ',
	'VIEW_TOPIC_STICKY'		=> 'Sabit: ',
	'VISIT_WEBSITE'			=> 'Siteyi ziyaret et',

	'WARNINGS'		=> 'Uyarılar',
	'WARN_USER'		=> 'Kullanıcıya uyarı ver',
	'WATCH_FORUM_CONFIRM'	=> 'Are you sure you wish to subscribe to this forum?',
	'WATCH_FORUM_DETAILED'	=> 'Are you sure you wish to subscribe to the forum “%s”?',
	'WATCH_TOPIC_CONFIRM'	=> 'Are you sure you wish to subscribe to this topic?',
	'WATCH_TOPIC_DETAILED'	=> 'Are you sure you wish to subscribe to the topic “%s”?',
	'WELCOME_SUBJECT'	=> 'Welcome to %s forums',
	'WEBSITE'		=> 'Website',
	'WHOIS'			=> 'Whois',
	'WHO_IS_ONLINE'		=> 'Kimler çevrimiçi',
	'WRONG_PASSWORD'	=> 'Yanlış bir şifre girdiniz.',

	'WRONG_DATA_COLOUR'		=> 'The colour value you entered is invalid.',
	'WRONG_DATA_JABBER'		=> 'The name you entered is not a valid Jabber account name.',
	'WRONG_DATA_LANG'		=> 'The language you specified is not valid.',
	'WRONG_DATA_POST_SD'		=> 'The post sort direction you specified is not valid.',
	'WRONG_DATA_POST_SK'		=> 'The post sort option you specified is not valid.',
	'WRONG_DATA_TOPIC_SD'		=> 'The topic sort direction you specified is not valid.',
	'WRONG_DATA_TOPIC_SK'		=> 'The topic sort option you specified is not valid.',
	'WROTE'				=> 'wrote',

	'YAHOO'			=> 'Yahoo Messenger',
	'YOUTUBE'		=> 'YouTube',
	'YEAR'			=> 'Yıl',
	'YEAR_MONTH_DAY'	=> '(YYYY-AA-GG)',
	'YES'			=> 'Evet',
	'YOU_LAST_VISIT'	=> 'Son ziyaretiniz: %s',

	'datetime'		=> array(
		'TODAY'		=> 'Bugün',
		'TOMORROW'	=> 'Yarın',
		'YESTERDAY'	=> 'Dün',
		'AGO'		=> array(
			0		=> 'biraz önce',
			1		=> '%d dakika önce',
			2		=> '%d dakika önce',
		),

		'Sunday'	=> 'Pazar',
		'Monday'	=> 'Pazartesi',
		'Tuesday'	=> 'Salı',
		'Wednesday'	=> 'Çarşamba',
		'Thursday'	=> 'Perşembe',
		'Friday'	=> 'Cuma',
		'Saturday'	=> 'Cumartesi',

		'Sun'		=> 'Pzr',
		'Mon'		=> 'Pts',
		'Tue'		=> 'Sal',
		'Wed'		=> 'Çar',
		'Thu'		=> 'Per',
		'Fri'		=> 'Cum',
		'Sat'		=> 'Cts',

		'January'	=> 'Ocak',
		'February'	=> 'Şubat',
		'March'		=> 'Mart',
		'April'		=> 'Nisan',
		'May'		=> 'Mayıs',
		'June'		=> 'Haziraz',
		'July'		=> 'Temmuz',
		'August'	=> 'Ağustos',
		'September'	=> 'Eylül',
		'October'	=> 'Ekim',
		'November'	=> 'Kasım',
		'December'	=> 'Aralık',

		'Jan'		=> 'Oca',
		'Feb'		=> 'Şub',
		'Mar'		=> 'Mar',
		'Apr'		=> 'Nis',
		'May_short'	=> 'May',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'Haz',
		'Jul'		=> 'Tem',
		'Aug'		=> 'Ağu',
		'Sep'		=> 'Eyl',
		'Oct'		=> 'Eki',
		'Nov'		=> 'Kas',
		'Dec'		=> 'Ara',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
		'timezones'		=> array(
		'UTC'			=> 'UTC',
		'UTC_OFFSET'		=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'	=> 'UTC+9',
		'Etc/GMT-8'	=> 'UTC+8',
		'Etc/GMT-7'	=> 'UTC+7',
		'Etc/GMT-6'	=> 'UTC+6',
		'Etc/GMT-5'	=> 'UTC+5',
		'Etc/GMT-4'	=> 'UTC+4',
		'Etc/GMT-3'	=> 'UTC+3',
		'Etc/GMT-2'	=> 'UTC+2',
		'Etc/GMT-1'	=> 'UTC+1',
		'Etc/GMT+1'	=> 'UTC-1',
		'Etc/GMT+2'	=> 'UTC-2',
		'Etc/GMT+3'	=> 'UTC-3',
		'Etc/GMT+4'	=> 'UTC-4',
		'Etc/GMT+5'	=> 'UTC-5',
		'Etc/GMT+6'	=> 'UTC-6',
		'Etc/GMT+7'	=> 'UTC-7',
		'Etc/GMT+8'	=> 'UTC-8',
		'Etc/GMT+9'	=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Africa/Abidjan',
		'Africa/Accra'		=> 'Africa/Accra',
		'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
		'Africa/Algiers'	=> 'Africa/Algiers',
		'Africa/Asmara'		=> 'Africa/Asmara',
		'Africa/Bamako'		=> 'Africa/Bamako',
		'Africa/Bangui'		=> 'Africa/Bangui',
		'Africa/Banjul'		=> 'Africa/Banjul',
		'Africa/Bissau'		=> 'Africa/Bissau',
		'Africa/Blantyre'	=> 'Africa/Blantyre',
		'Africa/Brazzaville'	=> 'Africa/Brazzaville',
		'Africa/Bujumbura'	=> 'Africa/Bujumbura',
		'Africa/Cairo'		=> 'Africa/Cairo',
		'Africa/Casablanca'	=> 'Africa/Casablanca',
		'Africa/Ceuta'		=> 'Africa/Ceuta',
		'Africa/Conakry'	=> 'Africa/Conakry',
		'Africa/Dakar'		=> 'Africa/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
		'Africa/Djibouti'	=> 'Africa/Djibouti',
		'Africa/Douala'		=> 'Africa/Douala',
		'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
		'Africa/Freetown'	=> 'Africa/Freetown',
		'Africa/Gaborone'	=> 'Africa/Gaborone',
		'Africa/Harare'		=> 'Africa/Harare',
		'Africa/Johannesburg'	=> 'Africa/Johannesburg',
		'Africa/Juba'		=> 'Africa/Juba',
		'Africa/Kampala'	=> 'Africa/Kampala',
		'Africa/Khartoum'	=> 'Africa/Khartoum',
		'Africa/Kigali'		=> 'Africa/Kigali',
		'Africa/Kinshasa'	=> 'Africa/Kinshasa',
		'Africa/Lagos'		=> 'Africa/Lagos',
		'Africa/Libreville'	=> 'Africa/Libreville',
		'Africa/Lome'		=> 'Africa/Lome',
		'Africa/Luanda'		=> 'Africa/Luanda',
		'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
		'Africa/Lusaka'		=> 'Africa/Lusaka',
		'Africa/Malabo'		=> 'Africa/Malabo',
		'Africa/Maputo'		=> 'Africa/Maputo',
		'Africa/Maseru'		=> 'Africa/Maseru',
		'Africa/Mbabane'	=> 'Africa/Mbabane',
		'Africa/Mogadishu'	=> 'Africa/Mogadishu',
		'Africa/Monrovia'	=> 'Africa/Monrovia',
		'Africa/Nairobi'	=> 'Africa/Nairobi',
		'Africa/Ndjamena'	=> 'Africa/Ndjamena',
		'Africa/Niamey'		=> 'Africa/Niamey',
		'Africa/Nouakchott'	=> 'Africa/Nouakchott',
		'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
		'Africa/Tripoli'	=> 'Africa/Tripoli',
		'Africa/Tunis'		=> 'Africa/Tunis',
		'Africa/Windhoek'	=> 'Africa/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'		=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'		=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'		=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'		=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'		=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'		=> 'America/Cambridge Bay',
		'America/Campo_Grande'		=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'		=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'		=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'		=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'		=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'		=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'		=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'		=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'		=> 'America/Los Angeles',
		'America/Lower_Princes'		=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'		=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'		=> 'America/Metlakatla',
		'America/Mexico_City'		=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'		=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'		=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'		=> 'America/Pangnirtung',
		'America/Paramaribo'		=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'	=> 'America/Recife',
		'America/Regina'	=> 'America/Regina',
		'America/Resolute'	=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'	=> 'America/Santarem',
		'America/Santiago'	=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'	=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'	=> 'America/Shiprock',
		'America/Sitka'		=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'	=> 'America/St. Johns',
		'America/St_Kitts'	=> 'America/St. Kitts',
		'America/St_Lucia'	=> 'America/St. Lucia',
		'America/St_Thomas'	=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'		=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'	=> 'America/Tijuana',
		'America/Toronto'	=> 'America/Toronto',
		'America/Tortola'	=> 'America/Tortola',
		'America/Vancouver'	=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'	=> 'America/Winnipeg',
		'America/Yakutat'	=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'		=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'		=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'		=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'		=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'		=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'		=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'		=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'		=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'		=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'		=> 'Asia/Omsk',
		'Asia/Oral'		=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> 'Asia/Seoul',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'		=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'		=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'		=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'	=> 'Australia/Currie',
		'Australia/Darwin'	=> 'Australia/Darwin',
		'Australia/Eucla'	=> 'Australia/Eucla',
		'Australia/Hobart'	=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'	=> 'Australia/Perth',
		'Australia/Sydney'	=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'		=> '01 Oca 2007, 13:37',
		'd M Y H:i'		=> '01 Oca 2007 13:37',
		'M jS, \'y, H:i'	=> 'Jan 1st, \'07, 13:37',
		'D M d, Y g:i a'	=> 'Pzt Oca 01, 2007 1:37 pm',
		'F jS, Y, g:i a'	=> 'Ocak 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'		=> 'Bugün, 13:37 / 01 Oca 2007, 13:37',
		'|F jS, Y|, g:i a'	=> 'Bugün, 1:37 pm / Ocak 1st, 2007, 1:37 pm',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'D M d, Y g:i a', // Mon Jan 01, 2007 1:37 pm

));
