<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

// Privacy policy and T&C
$lang = array_merge($lang, array(
	'TERMS_OF_USE_CONTENT'	=> '“%1$s” (bundan böyle “biz”, “bize”, “bizim”, “%1$s”, “%2$s” olarak anılacaktır) sitesine erişim sağlayarak , yasal olarak sınırlı olmayı ve aşağıdaki koşulları kabul ediyorsunuz. Eğer yasal olarak sınırlı olan alttaki koşulların tümünü kabul etmiyorsanız o zaman lütfen "%1$s" mesaj panosuna giriş yapmayın ve/veya kullanmayın. Bunları herhangi bir zamanda değiştirebiliriz ve sizi bilgilendirmek için elimizden gelenin en iyisini yaparız; ancak kendiniz düzenli olarak bu koşulları tekrar gözden geçirmeniz ihtiyatlı olacaktır çünkü "%1$s" mesaj panosunu kullanmaya devam etmeniz, yasal olarak sınırlı olan bu koşulların güncellenmesi ve/veya düzenlenmesi durumunda meydana gelebilecek değişiklikleri de kabul ettiğiniz anlamına gelir.
	<br><br>
	Bizim forumumuz phpBB (bundan böyle “onlar”, “onlara”, “onların”, “phpBB yazılımı”, “www.phpbb.com”, “phpBB Limited”, “phpBB Şartları” olarak anılacaktır) tarafından desteklenmektedir; bu da “<a href="http://opensource.org/licenses/gpl-2.0.php">GNU General Public License v2</a>” (bundan böyle “GPL”) kapsamında yayınlanan bir forum yazılımıdır ve <a href="https://www.phpbb.com/">www.phpbb.com</a> üzerinden indirilebilir. phpBB yazılımı yalnızca internet tabanlı tartışmaları kolaylaştırır; phpBB Limited izin verilen içerik ve/veya davranış olarak izin verdiğimiz ve/veya izin vermediğimiz şeylerden sorumlu değildir. phpBB hakkında daha fazla bilgi için lütfen bakınız: <a href="https://www.phpbb.com/">https://www.phpbb.com/</a>.
	<br><br>
	Küfürlü, müstehcen, kaba, iftira niteliğinde, nefret dolu, tehdit edici, sekse yönelik veya ülkenizin kanunlarını çiğneyici içerikler göndermemeyi kabul ediyorsunuz, "%1$s" mesaj panosu hangi ülkede barındırılıyorsa o ülkenin kanunları veya Uluslararası kanunlar geçerlidir. Bunu yapmanız tarafımızca gerekli görülmesi halinde İnternet Servis Sağlayıcınıza bildirimde bulunulması ile derhal ve kalıcı olarak yasaklanmanıza yol açabilir. Bu koşulların uygulanmasına yardımcı olmak için tüm gönderilerin IP adresleri kaydedilir. “%1$s” olarak uygun görmemiz halinde herhangi bir konuyu herhangi bir zamanda kaldırma, düzenleme, taşıma veya kapatma hakkına sahip olduğumuzu kabul ediyorsunuz. Kullanıcı olarak girdiğiniz her türlü bilginin bir veri tabanında saklanmasını kabul etmiş oluyorsnuz. Her ne kadar bu bilgiler sizin bilginiz dışında üçüncü şahıslara verilmeyecek olsa da, herhangi bir hack saldırısı sonucunda bu bilgiler dağılırsa bundan "%1$s" veya phpBB sorumlu tutulamaz.
	',

	'PRIVACY_POLICY'		=> 'Bu politikada herhangi bir oturum için tarafınızca kullanım sırasında toplanan bilgilerin (bundan böyle “bilgilerin” olarak anılacaktır) “%1$s” ile birlikte bağlı şirketler (bundan böyle “biz”, “bize”, “bizim”, “%1$s”, “%2$s” olarak anılacaktır) ve phpBB (bundan böyle “onlar”, “onlara”, “onların”, “phpBB yazılımı”, “www.phpbb.com”, “phpBB Limited”, “phpBB Şartları” olarak anılacaktır) tarafından nasıl kullanıldığı ayrıntılı olarak açıklanmaktadır.
	<br><br>
	Bilgileriniz iki şekilde toplanmaktadır. İlki, "%1$s" mesaj panosunu dolaşırken bilgisayarınızın web tarayıcısının geçici dosyalarına indirilen küçük metin dosyaları olarak phpBB yazılımı belirli sayıda çerezler oluşturacaktır. İlk iki çerez phpBB yazılımı tarafından size otomatik olarak atanan yalnızca bir kullanıcı tanımlayıcısı (bundan böyle "kullanıcı kimliği" olarak anılacaktır) ve bir anonim oturum tanımlayıcısı (bundan böyle "oturum kimliği" olarak anılacaktır) içerir. “%1$s” içindeki konulara göz attığınızda üçüncü bir çerez oluşturulacak ve hangi konuların okunduğunu depolamak için kullanılacak, böylece kullanıcı deneyiminiz iyileştirilecektir.
	<br><br>
	Ayrıca “%1$s” mesaj panosunu dolaşırken phpBB yazılımının dışında çerezler oluşturabiliriz ancak bunlar yalnızca phpBB yazılımı tarafından oluşturulan sayfaları kapsaması amaçlanan bu belgenin kapsamı dışındadır. Bilgilerinizi toplamamızın ikinci yolu, bize sunduğunuz bilgilerdir. Bu bunlarla sınırlı olabilir veya olmayabilir: anonim kullanıcı olarak paylaşım yapmak (bundan böyle "anonim gönderiler" olarak anılacaktır), “%1$s” mesaj panosuna kaydınız (bundan sonra “hesabınız” olarak anılacaktır) ve kayıt olduktan sonra ve giriş yaparken tarafınızca gönderilen gönderiler (bundan sonra "gönderileriniz" olarak anılacaktır).
	<br><br>
	Hesabınız en azından benzersiz şekilde tanımlanabilen bir ad (bundan sonra "kullanıcı adınız" olarak anılacaktır), hesabınıza giriş yapmak için kullanılan kişisel bir şifre (bundan sonra “şifreniz” olarak anılacaktır) ve kişisel geçerli eposta adresi (bundan sonra "e-postanız" olarak anılacaktır) içerecektir. “%1$s” sitesinde hesabınıza ait bilgileriniz hostumuzun barındığı ülkedeki kanunlar kapsamında veri-koruma yöntemiyle korunmaktadır. Kayıt işlemi sırasında "%1$s" tarafından istenen kullanıcı adınız, şifreniz ve e-posta adresinizin dışında her türlü bilginin zorunlu ya da isteğe bağlı olup olmaması "%1$s" şirketinin takdirine bağlıdır. Her durumda, hesabınızdaki hangi bilgilerin herkese açık olarak görüntüleneceğini seçme seçeneğiniz vardır. Ayrıca, hesabınızda, phpBB yazılımı tarafından otomatik olarak oluşturulan e-postaları kabul etme veya devre dışı bırakma seçeneğine sahipsiniz.
	<br><br>
	Şifreniz güvenli olması için şifrelenmiştir (tek yönlü bir hash). Ancak aynı şifreyi farklı birçok web sitesinde tekrar kullanmamanız önerilir. Şifreniz "%1$s" mesaj panosundaki hesabınıza erişim için gerekmektedir, ayrıca lütfen şifrenizi dikkatli koruyun ve hiçbir surette "%1$s" ile bağlantılı bir kimseye, phpBB veya bir diğer 3. parti kişi veya sitelere, şifreniz için soru sormayın. Hesabınızın şifresini unutmanız durumunda, phpBB yazılımının sunduğu “Şifremi unuttum” özelliğini kullanabilirsiniz. Bu işlem sizden kullanıcı adınızı ve e-posta adresinizi girmenizi isteyecek, ardından phpBB yazılımı hesabınızı geri almak için yeni bir şifre oluşturacaktır.
	',
));

// Common language entries
$lang = array_merge($lang, array(
	'ACCOUNT_ACTIVE'				=> 'Hesabınız şimdi aktifleştirildi. Kayıt olduğunuz için teşekkürler.',
	'ACCOUNT_ACTIVE_ADMIN'			=> 'Hesap şimdi aktifleştirildi.',
	'ACCOUNT_ACTIVE_PROFILE'		=> 'Hesabınız şimdi başarıyla yeniden aktifleştirildi.',
	'ACCOUNT_ADDED'					=> 'Kayıt olduğunuz için teşekkürler, hesabınız oluşturuldu.',
	'ACCOUNT_COPPA'					=> 'Hesabınız oluşturuldu ancak onaylanması gerekiyor. Ayrıntılar için lütfen epostanızı kontrol edin.',
	'ACCOUNT_EMAIL_CHANGED'			=> 'Hesabın güncellendi. Ancak bu mesaj panosu, eposta değişikliklerinde hesabın yeniden aktifleştirilmesini gerektirir. Belirttiğiniz yeni eposta adresine bir aktivasyon anahtarı gönderildi. Daha fazla bilgi için lütfen epostanızı kontrol edin.',
	'ACCOUNT_EMAIL_CHANGED_ADMIN'	=> 'Hesabın güncellendi. Ancak bu mesaj panosu, eposta değişikliklerinde hesabın yöneticiler tarafından yeniden aktifleştirilmesini gerektirir. Onlara bir eposta gönderildi ve hesabınız yeniden aktifleştirildiğinde size bilgi verilecek.',
	'ACCOUNT_INACTIVE'				=> 'Hesabınız oluşturuldu. Ancak bu mesaj panosu hesap aktivasyonunu gerektirir. Verdiğiniz eposta adresine bir aktivasyon anahtarı gönderildi. Daha fazla bilgi için lütfen epostanızı kontrol edin ve ayrıca istenmeyen posta kutunuzu da kontrol ettiğinizden emin olun. Eposta sağlayıcınıza bağlı olarak epostayı almanız biraz zaman alabilir.',
	'ACCOUNT_INACTIVE_ADMIN'		=> 'Hesabınız oluşturuldu. Ancak bu mesaj panosu yönetici grubu tarafından hesabın etkinleştirilmesini gerektirir. Onlara bir eposta gönderildi ve hesabınız aktifleştirildiğinde size bilgi verilecek.',
	'ACTIVATION_EMAIL_SENT'			=> 'Aktivasyon epostası eposta adresinize gönderildi.',
	'ACTIVATION_EMAIL_SENT_ADMIN'	=> 'Aktivasyon epostası yöneticilerin eposta adreslerine gönderildi.',
	'ADD'							=> 'Ekle',
	'ADD_BCC'						=> 'Ekle [BCC]',
	'ADD_FOES'						=> 'Yeni engelliler ekle',
	'ADD_FOES_EXPLAIN'				=> 'Farklı bir satıra birden fazla kullanıcı adı girebilirsiniz.',
	'ADD_FOLDER'					=> 'Klasör ekle',
	'ADD_FRIENDS'					=> 'Yeni arkadaşlar ekle',
	'ADD_FRIENDS_EXPLAIN'			=> 'Farklı bir satıra birden fazla kullanıcı adı girebilirsiniz.',
	'ADD_NEW_RULE'					=> 'Yeni kural ekle',
	'ADD_RULE'						=> 'Kural ekle',
	'ADD_TO'						=> 'Ekle [Alıcı]',
	'ADD_USERS_UCP_EXPLAIN'			=> 'Here you can add new users to the group. You may select whether this group becomes the new default for the selected users. Please enter each username on a separate line.',
	'ADMIN_EMAIL'					=> 'Yöneticiler beni eposta ile bilgilendirebilir',
	'AGREE'							=> 'Bu şartları kabul ediyorum',
	'ALLOW_PM'						=> 'Kullanıcıların size özel mesaj göndermesine izin verin',
	'ALLOW_PM_EXPLAIN'				=> 'Yöneticilerin ve moderatörlerin size her zaman mesaj gönderebileceğini unutmayın.',
	'ALREADY_ACTIVATED'				=> 'Hesabınızı zaten aktif hale getirdiniz.',
	'ATTACHMENTS_EXPLAIN'			=> 'Bu panoya gönderdiğiniz gönderilerdeki eklerin listesidir.',
	'ATTACHMENTS_DELETED'			=> 'Ekler başarıyla silindi.',
	'ATTACHMENT_DELETED'			=> 'Ek başarıyla silindi.',
	'ATTACHMENT_LOCKED'				=> 'Bu konu kilitlendi, ek silemezsiniz.',
	'AUTOLOGIN_SESSION_KEYS_DELETED'=> 'Seçilen "Beni hatırla" giriş anahtarları başarıyla silindi.',
	'AVATAR_CATEGORY'				=> 'Kategori',
	'AVATAR_DRIVER_GRAVATAR_TITLE'	=> 'Gravatar',
	'AVATAR_DRIVER_GRAVATAR_EXPLAIN'=> 'Gravatar birden fazla web sitesinde aynı avatarı kullanmanıza olanak tanıyan bir hizmettir. Daha fazla bilgi için <a href="http://www.gravatar.com/">Gravatar</a> sitesini ziyaret edin.',
	'AVATAR_DRIVER_LOCAL_TITLE'		=> 'Galeri avatarı',
	'AVATAR_DRIVER_LOCAL_EXPLAIN'	=> 'Avatarınızı yerel olarak mevcut olan avatarlar arasından seçebilirsiniz.',
	'AVATAR_DRIVER_REMOTE_TITLE'	=> 'Uzak avatar',
	'AVATAR_DRIVER_REMOTE_EXPLAIN'	=> 'Başka bir web sitesinden avatar resimlerine bağlantı verin.',
	'AVATAR_DRIVER_UPLOAD_TITLE'	=> 'Avatar yükle',
	'AVATAR_DRIVER_UPLOAD_EXPLAIN'	=> 'Kendi özel avatarını yükle',
	'AVATAR_EXPLAIN'				=> 'Maksimum boyutlar; genişlik: %1$s, yükseklik: %2$s, dosya boyutu: %3$.2f KiB.',
	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maksimum boyutlar; genişlik: %1$s, yükseklik: %2$s.',
	'AVATAR_FEATURES_DISABLED'		=> 'Avatar işlevi şu anda devre dışı.',
	'AVATAR_GALLERY'				=> 'Yerel galeri',
	'AVATAR_GENERAL_UPLOAD_ERROR'	=> 'Avatar yüklenemedi %s.',
	'AVATAR_NOT_ALLOWED'			=> 'Avatarlara izin verilmediğinden avatarınız görüntülenemiyor.',
	'AVATAR_PAGE'					=> 'Sayfa',
	'AVATAR_SELECT'					=> 'Avatarını seç',
	'AVATAR_TYPE'					=> 'Avatar türü',
	'AVATAR_TYPE_NOT_ALLOWED'		=> 'Mevcut avatarınız türüne izin verilmediğinden görüntülenemiyor.',

	'BACK_TO_DRAFTS'			=> 'Kaydedilen taslaklara dön',
	'BACK_TO_LOGIN'				=> 'Giriş ekranına dön',
	'BIRTHDAY'					=> 'Doğum günü',
	'BIRTHDAY_EXPLAIN'			=> 'Bir yıl ayarlamak doğum gününüz olduğunda yaşınızı listeleyecektir.',
	'BOARD_DATE_FORMAT'			=> 'Tarih formatım',
	'BOARD_DATE_FORMAT_EXPLAIN'	=> 'Söz dizimi PHP <a href="https://www.php.net/manual/datetime.format.php">tarih fonksiyonları</a> ile aynı formatı kullanır.',
	'BOARD_LANGUAGE'			=> 'Dilim',
	'BOARD_STYLE'				=> 'Pano stilim',
	'BOARD_TIMEZONE'			=> 'Saat dilimim',
	'BOOKMARKS'					=> 'Yer imleri',
	'BOOKMARKS_EXPLAIN'			=> 'İleride başvurmak üzere konuları yer imlerinize ekleyebilirsiniz. Silmek istediğiniz herhangi bir yer iminin onay kutusunu seçin ve ardından <em>İşaretli yer imlerini kaldır</em> butonuna basın.',
	'BOOKMARKS_DISABLED'		=> 'Yer imleri bu panoda devre dışı bırakıldı',
	'BOOKMARKS_REMOVED'			=> 'Yer imleri başarıyla kaldırıldı.',

	'CANNOT_EDIT_MESSAGE_TIME'	=> 'Artık bu mesajı düzenleyemez veya silemezsiniz.',
	'CANNOT_MOVE_TO_SAME_FOLDER'=> 'Mesajlar kaldırmak istediğiniz klasöre taşınamaz.',
	'CANNOT_MOVE_FROM_SPECIAL'	=> 'Mesajlar giden kutusundan taşınamaz.',
	'CANNOT_RENAME_FOLDER'		=> 'Bu klasör yeniden adlandırılamaz.',
	'CANNOT_REMOVE_FOLDER'		=> 'Bu klasör kaldırılamaz.',
	'CHANGE_DEFAULT_GROUP'		=> 'Varsayılan grubu değiştir',
	'CHANGE_PASSWORD'			=> 'Şifreyi değiştir',
	'CLICK_GOTO_FOLDER'			=> '%1$s“%3$s” klasörüne git%2$s',
	'CLICK_RETURN_FOLDER'		=> '%1$s“%3$s” klasörüne dön%2$s',
	'CONFIRMATION'				=> 'Kayıt doğrulaması',
	'CONFIRM_CHANGES'			=> 'Değişiklikleri onayla',
	'CONFIRM_EXPLAIN'			=> 'Otomatik kayıtları önlemek için mesaj panosu bir doğrulama kodu girmenizi gerektirir. Kod aşağıda görmeniz gereken resimde gösterilmektedir. Görme engelliyseniz veya bu kodu başka bir şekilde okuyamıyorsanız lütfen %sPano Yöneticisi%s ile iletişime geçin.',
	'VC_REFRESH'				=> 'Doğrulama kodunu yenile',
	'VC_REFRESH_EXPLAIN'		=> 'Kodu okuyamıyorsanız butonuna tıklayarak yeni bir kod talep edebilirsiniz.',

	'CONFIRM_PASSWORD'			=> 'Şifreyi onayla',
	'CONFIRM_PASSWORD_EXPLAIN'	=> 'Şifrenizi yalnızca yukarıda değiştirdiyseniz onaylamanız gerekir.',
	'COPPA_BIRTHDAY'			=> 'Kayıt işlemine devam etmek için lütfen ne zaman doğduğunuzu bildirin.',
	'COPPA_COMPLIANCE'			=> 'COPPA uyumluluk',
	'COPPA_EXPLAIN'				=> 'Gönder’e tıkladığınızda hesabınızın oluşturulacağını lütfen unutmayın. Ancak bir ebeveyniniz veya vasiniz kaydınızı onaylayana kadar aktifleştirilemez. Gerekli formun bir kopyası, nereye göndereceğinize ilişkin ayrıntıları içeren epostayla gönderilecektir.',
	'CREATE_FOLDER'				=> 'Klasör ekle…',
	'CURRENT_IMAGE'				=> 'Mevcut resim',
	'CURRENT_PASSWORD'			=> 'Mevcut şifre',
	'CURRENT_PASSWORD_EXPLAIN'	=> 'Eposta adresinizi veya kullanıcı adınızı değiştirmek istiyorsanız mevcut şifrenizi girmeniz gerekir.',
	'CURRENT_CHANGE_PASSWORD_EXPLAIN' => 'Şifrenizi, eposta adresinizi veya kullanıcı adınızı değiştirmek için mevcut şifrenizi girmeniz gerekir.',
	'CUR_PASSWORD_EMPTY'		=> 'Mevcut şifrenizi girmediniz.',
	'CUR_PASSWORD_ERROR'		=> 'Mevcut şifrenizi yanlış girdiniz.',
	'CUSTOM_DATEFORMAT'			=> 'Özel…',

	'DEFAULT_ACTION'			=> 'Varsayilan eylem',
	'DEFAULT_ACTION_EXPLAIN'	=> 'Yukarıdakilerin hiç biri uygulanabilir değilse bu eylem tetiklenecek.',
	'DEFAULT_ADD_SIG'			=> 'Varsayılan olarak imzamı ekle',
	'DEFAULT_BBCODE'			=> 'Varayılan olarak BBCode etkinleştir',
	'DEFAULT_NOTIFY'			=> 'Varsayılan olarak cevaplar üzerine beni bilgilendir',
	'DEFAULT_SMILIES'			=> 'Varsayılan olarak ifadeleri etkinleştir',
	'DEFINED_RULES'				=> 'Tanımlanmış kurallar',
	'DELETED_TOPIC'				=> 'Konu kaldırıldı.',
	'DELETE_ATTACHMENT'			=> 'Ek sil',
	'DELETE_ATTACHMENTS'		=> 'Ekleri sil',
	'DELETE_ATTACHMENT_CONFIRM'	=> 'Bu eki silmek istediğinize emin misiniz?',
	'DELETE_ATTACHMENTS_CONFIRM'=> 'Bu ekleri silmek istediğinize emin misiniz?',
	'DELETE_AVATAR'				=> 'Resmi sil',
	'DELETE_COOKIES_CONFIRM'	=> 'Bu panonun ayarladığı tüm çerezleri silmek istediğinize emin misiniz?',
	'DELETE_MARKED_PM'			=> 'İşaretli mesajları sil',
	'DELETE_MARKED_PM_CONFIRM'	=> 'Tüm işaretli mesajları silmek istediğinize emin misiniz?',
	'DELETE_OLDEST_MESSAGES'	=> 'Eski mesajları sil',
	'DELETE_MESSAGE'			=> 'Mesajı sil',
	'DELETE_MESSAGE_CONFIRM'	=> 'Bu özel mesajı silmek istediğinize emin misiniz?',
	'DELETE_MESSAGES_IN_FOLDER'	=> 'Kaldırılan klasördeki tüm mesajları sil',
	'DELETE_RULE'				=> 'Kuralı sil',
	'DELETE_RULE_CONFIRM'		=> 'Bu kuralı silmek istediğinize emin misiniz?',
	'DEMOTE_SELECTED'			=> 'Seçileni indirge',
	'DISABLE_CENSORS'			=> 'Kelime sansürlemeyi etkinleştir',
	'DISPLAY_GALLERY'			=> 'Galeriyi görüntüle',
	'DOWNLOADS'					=> 'İndirmeler',
	'DRAFTS_DELETED'			=> 'Tüm seçili taslaklar başarıyla silindi.',
	'DRAFTS_EXPLAIN'			=> 'Buradan kaydettiğiniz taslakları görüntüleyebilir, düzenleyebilir ve silebilirsiniz.',
	'DRAFT_UPDATED'				=> 'Taslak başarıyla güncellendi.',

	'EDIT_DRAFT_EXPLAIN'		=> 'Burada taslağınızı düzenleyebilirsiniz. Taslaklar ek ve anket bilgisi içermez.',
	'EMAIL_BANNED_EMAIL'		=> 'Girdiğiniz eposta adresinin kullanılmasına izin verilmiyor.',
	'EMAIL_REMIND'				=> 'Bu, hesabınızla ilişkilendirilmiş eposta adresi olmalıdır. Kullanıcı kontrol paneli aracılığıyla değiştirmediyseniz hesabınızı kaydettiğiniz eposta adresidir.',
	'EMAIL_TAKEN_EMAIL'			=> 'Girilen eposta adresi zaten kullanılıyor.',
	'EMPTY_DRAFT'				=> 'Değişikliklerinizi göndermek için bir mesaj girmelisiniz.',
	'EMPTY_DRAFT_TITLE'			=> 'Taslak başlığı girmelisiniz.',
	'EXPORT_AS_XML'				=> 'XML olarak dışa aktar',
	'EXPORT_AS_CSV'				=> 'CSV olarak dışa aktar',
	'EXPORT_AS_CSV_EXCEL'		=> 'CSV olarak dışa aktar (Excel)',
	'EXPORT_AS_TXT'				=> 'TXT olarak dışa aktar',
	'EXPORT_AS_MSG'				=> 'MSG olarak dışa aktar',
	'EXPORT_FOLDER'				=> 'Bu görünümü dışa aktar',

	'FIELD_REQUIRED'					=> '“%s” alanı doldurulmalıdır.',
	'FIELD_TOO_SHORT'					=> array(
		1	=> '“%2$s” alanı çok kısa, minimum %1$d karakter gerekli.',
		2	=> '“%2$s” alanı çok kısa, minimum %1$d karakter gerekli.',
	),
	'FIELD_TOO_LONG'					=> array(
		1	=> '“%2$s” alanı çok uzun, maksimum %1$d karaktere izin veriliyor.',
		2	=> '“%2$s” alanı çok uzun, maksimum %1$d karaktere izin veriliyor.',
	),
	'FIELD_TOO_SMALL'					=> '“%2$s” değeri çok küçük, minimum %1$d değeri gerekli.',
	'FIELD_TOO_LARGE'					=> '“%2$s” değeri çok büyük, maksimum %1$d değerine izin veriliyor.',
	'FIELD_INVALID_CHARS_INVALID'		=> '“%s” alanı geçersiz karakterler içeriyor.',
	'FIELD_INVALID_CHARS_NUMBERS_ONLY'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca rakamlara izin verilir.',
	'FIELD_INVALID_CHARS_ALPHA_DOTS'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca alfanumerik ya da . karakterlerine izin verilir.',
	'FIELD_INVALID_CHARS_ALPHA_ONLY'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca alfanumerik karakterlere izin verilir.',
	'FIELD_INVALID_CHARS_ALPHA_PUNCTUATION'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca alfanumerik ya da _,-. karakterlerine izin verilir ve ilk karakter alfabetik olmalıdır.',
	'FIELD_INVALID_CHARS_ALPHA_SPACERS'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca alfanumerik, boşluk ya da -+_[] karakterlerine izin verilir.',
	'FIELD_INVALID_CHARS_ALPHA_UNDERSCORE'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca alfanumerik ya da _ karakterlerine izin verilir.',
	'FIELD_INVALID_CHARS_LETTER_NUM_DOTS'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca harf, rakam ya da . karakterlerine izin verilir.',
	'FIELD_INVALID_CHARS_LETTER_NUM_ONLY'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca harf ve rakam karakterlerine izin verilir.',
	'FIELD_INVALID_CHARS_LETTER_NUM_PUNCTUATION'	=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca harf, rakam ya da _,-. karakterlerine izin verilir ve and ilk karakter alfabetik olmalıdır.',
	'FIELD_INVALID_CHARS_LETTER_NUM_SPACERS'		=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca harf, rakam, boşluk ya da -+_[] karakterlerine izin verilir.',
	'FIELD_INVALID_CHARS_LETTER_NUM_UNDERSCORE'		=> '“%s” alanı geçersiz karakterler içeriyor, yalnızca harf, rakam ya da _ karakterlerine izin verilir.',
	'FIELD_INVALID_DATE'				=> '“%s” alanı geçersiz bir tarih içeriyor.',
	'FIELD_INVALID_URL'					=> '“%s” alanı geçersiz bir url içeriyor.',
	'FIELD_INVALID_VALUE'				=> '“%s” alanı geçersiz bir değer içeriyor.',

	'FOE_MESSAGE'				=> 'Engelliden mesaj',
	'FOES_EXPLAIN'				=> 'Foes are users which will be ignored by default. Posts by these users will not be fully visible. Private messages from foes are still permitted. Please note that you cannot ignore moderators or administrators.',
	'FOES_UPDATED'				=> 'Engelliler listeniz başarıyla güncellendi.',
	'FOLDER_ADDED'				=> 'Klasör başarıyla eklendi.',
	'FOLDER_MESSAGE_STATUS'		=> array(
		1	=> '%1$s üzerinden %2$d tanesi depolandı',
		2	=> '%1$s üzerinden %2$d tanesi depolandı',
	),
	'FOLDER_NAME_EMPTY'			=> 'Bu klasöre bir ad girmelisiniz.',
	'FOLDER_NAME_EXIST'			=> '<strong>%s</strong> klasörü zaten mevcut.',
	'FOLDER_OPTIONS'			=> 'Klasör seçenekleri',
	'FOLDER_RENAMED'			=> 'Klasör başarıyla yeniden adlandırıldı.',
	'FOLDER_REMOVED'			=> 'Klasör başarıyla kaldırıldı.',
	'FOLDER_STATUS_MSG'			=> array(
		1	=> 'Klasör doluluğu %3$d%% (%1$s üzerinden %2$d tanesi depolandı)',
		2	=> 'Klasör doluluğu %3$d%% (%1$s üzerinden %2$d tanesi depolandı)',
	),
	'FORWARD_PM'				=> 'ÖM ilet',
	'FORCE_PASSWORD_EXPLAIN'	=> 'Before you may continue browsing the board you are required to change your password.',
	'FRIEND_MESSAGE'			=> 'Arkadaştan mesaj',
	'FRIENDS'					=> 'Arkadaşlar',
	'FRIENDS_EXPLAIN'			=> 'Arkadaşlar sık iletişim kurduğunuz üyelere hızlı erişmenizi sağlar. Şablonun ilgili desteği varsa, bir arkadaşınızın yaptığı gönderiler vurgulanabilir.',
	'FRIENDS_OFFLINE'			=> 'Çevrimdışı',
	'FRIENDS_ONLINE'			=> 'Çevrimiçi',
	'FRIENDS_UPDATED'			=> 'Arkadaş listeniz başarıyla güncellendi.',
	'FULL_FOLDER_OPTION_CHANGED'=> 'The action to take when a folder is full has been changed successfully.',
	'FWD_ORIGINAL_MESSAGE'		=> '-------- Orjinal Mesaj --------',
	'FWD_SUBJECT'				=> 'Konu: %s',
	'FWD_DATE'					=> 'Zaman: %s',
	'FWD_FROM'					=> 'Gönderici: %s',
	'FWD_TO'					=> 'Gönderilen: %s',

	'GLOBAL_ANNOUNCEMENT'		=> 'Genel duyuru',

	'GRAVATAR_AVATAR_EMAIL'			=> 'Gravatar eposta',
	'GRAVATAR_AVATAR_EMAIL_EXPLAIN'	=> 'Enter the email address you used for registering your account on <a href="http://www.gravatar.com/">Gravatar</a>.',
	'GRAVATAR_AVATAR_SIZE'			=> 'Avatar dimensions',
	'GRAVATAR_AVATAR_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',

	'HIDE_ONLINE'				=> 'Çevrimiçi durumumu gizle',
	'HIDE_ONLINE_EXPLAIN'		=> 'Changing this setting won’t become effective until your next visit to the board.',
	'HOLD_NEW_MESSAGES'			=> 'Do not accept new messages (New messages will be held back until enough space is available)',
	'HOLD_NEW_MESSAGES_SHORT'	=> 'New messages will be held back',

	'IF_FOLDER_FULL'			=> 'Klasör doluysa',
	'IMPORTANT_NEWS'			=> 'Önemli duyurular',
	'INVALID_USER_BIRTHDAY'			=> 'Girilen doğum günü geçerli bir tarih değil.',
	'INVALID_CHARS_USERNAME'	=> 'Kullanıcı adı yasaklı karakterler içeriyor.',
	'INVALID_EMOJIS_USERNAME'	=> 'Kullanıcı adı yasaklı karakterler içeriyor (Emoji).',
	'INVALID_CHARS_NEW_PASSWORD'=> 'Şifre gerekli karakterleri içermiyor.',
	'ITEMS_REQUIRED'			=> '* ile işaretlenen alanlar zorunlu profil alanlarıdır ve doldurulması gerekmektedir.',

	'JOIN_SELECTED'				=> 'Seçilenlere katıl',

	'LANGUAGE'					=> 'Dil',
	'LINK_REMOTE_AVATAR'		=> 'Site dışı link',
	'LINK_REMOTE_AVATAR_EXPLAIN'=> 'Enter the URL of the location containing the avatar image you wish to link to.',
	'LINK_REMOTE_SIZE'			=> 'Avatar boyutları',
	'LINK_REMOTE_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',
	'LOGIN_EXPLAIN_UCP'			=> 'Please login in order to access the User Control Panel.',
	'LOGIN_LINK'					=> 'Link or register your account on an external service with your board account',
	'LOGIN_LINK_EXPLAIN'			=> 'You have attempted to login with an external service that is not yet connected to an account on this board. You must now either link this account to an existing account or create a new account.',
	'LOGIN_LINK_MISSING_DATA'		=> 'Data that is necessary to link your account with an external service is not available. Please restart the login process.',
	'LOGIN_LINK_NO_DATA_PROVIDED'	=> 'No data has been provided to this page to link an external account to a forum account. Please contact the board administrator if you continue to experience problems.',
	'LOGIN_KEY'					=> 'Giriş anahtarı',
	'LOGIN_TIME'				=> 'Giriş zamanı',
	'LOGIN_REDIRECT'			=> 'You have been successfully logged in.',
	'LOGOUT_FAILED'				=> 'You were not logged out, as the request did not match your session. Please contact the board administrator if you continue to experience problems.',
	'LOGOUT_REDIRECT'			=> 'You have been successfully logged out.',

	'MARK_IMPORTANT'				=> 'Önemli olarak işaretle/işareti kaldır',
	'MARKED_MESSAGE'				=> 'İşaretli mesaj',
	'MAX_FOLDER_REACHED'			=> 'Maximum number of allowed user defined folders reached.',
	'MESSAGE_BY_AUTHOR'				=> 'by',
	'MESSAGE_COLOURS'				=> 'Mesaj renkleri',
	'MESSAGE_DELETED'				=> 'Mesaj başarıyla silindi.',
	'MESSAGE_EDITED'				=> 'Mesaj başarıyla düzenlendi.',
	'MESSAGE_HISTORY'				=> 'Message history',
	'MESSAGE_REMOVED_FROM_OUTBOX'	=> 'Bu mesaj onun sahibi tarafından silindi.',
	'MESSAGE_REPORTED_MESSAGE'		=> 'Raporlu mesaj',
	'MESSAGE_SENT_ON'				=> 'on',
	'MESSAGE_STORED'				=> 'This message has been sent successfully.',
	'MESSAGE_TO'					=> 'To',
	'MESSAGES_DELETED'				=> 'Mesajlar başarıyla silindi',
	'MOVE_DELETED_MESSAGES_TO'		=> 'Kaldırılan klasördeki mesajları bu klasöre taşı',
	'MOVE_DOWN'						=> 'Aşağı taşı',
	'MOVE_MARKED_TO_FOLDER'			=> 'İşaretlileri %s klasörüne taşı',
	'MOVE_PM_ERROR'					=> array(
		1	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s was moved.',
		2	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s were moved.',
	),
	'MOVE_TO_FOLDER'				=> 'Klasöre taşı',
	'MOVE_UP'						=> 'Yukarı taşı',

	'NEW_FOLDER_NAME'				=> 'Yeni klasör adı',
	'NEW_PASSWORD'					=> 'Yeni şifre',
	'NEW_PASSWORD_CONFIRM_EMPTY'	=> 'Onay şifresini girmediniz.',
	'NEW_PASSWORD_ERROR'			=> 'Girdiğiniz şifreler eşleşmiyor.',

	'NOTIFICATIONS_MARK_ALL_READ'						=> 'Tüm bildirimleri okundu olarak işaretle',
	'NOTIFICATIONS_MARK_ALL_READ_CONFIRM'				=> 'Tüm bildirimleri okundu olarak işaretlemek istediğinize emin misiniz?',
	'NOTIFICATIONS_MARK_ALL_READ_SUCCESS'				=> 'Tüm bildirimler okundu olarak işaretlendi.',
	'NOTIFICATION_GROUP_MISCELLANEOUS'					=> 'Çeşitli Bildirimler',
	'NOTIFICATION_GROUP_MODERATION'						=> 'Moderasyon Bildirimleri',
	'NOTIFICATION_GROUP_ADMINISTRATION'					=> 'Yönetim Bildirimleri',
	'NOTIFICATION_GROUP_POSTING'						=> 'Gönderi Bildirimleri',
	'NOTIFICATION_METHOD_BOARD'							=> 'Bildirimler',
	'NOTIFICATION_METHOD_EMAIL'							=> 'Eposta',
	'NOTIFICATION_METHOD_JABBER'						=> 'Jabber',
	'NOTIFICATION_TYPE'									=> 'Bildirim türü',
	'NOTIFICATION_TYPE_BOOKMARK'						=> 'Birinin yer imlerinizdeki bir konuya yanıt vermesi',
	'NOTIFICATION_TYPE_GROUP_REQUEST'					=> 'Birinin liderliğini yaptığınız bir gruba katılmak istemesi',
	'NOTIFICATION_TYPE_FORUM'							=> 'Birinin abone olduğunuz bir forumda bir konuya yanıt vermesi',
	'NOTIFICATION_TYPE_IN_MODERATION_QUEUE'				=> 'Bir mesajın veya konunun onaylanmasının gerekmesi',
	'NOTIFICATION_TYPE_MODERATION_QUEUE'				=> 'Bir maderatör tarafından konularınızın/mesajlarınızın onaylaması ve reddedilmesi',
	'NOTIFICATION_TYPE_PM'								=> 'Birinin size özel mesaj göndermesi',
	'NOTIFICATION_TYPE_POST'							=> 'Birinin abone olduğunuz bir konuya cevap yazması',
	'NOTIFICATION_TYPE_QUOTE'							=> 'Birinin bir measjında sizden alıntı yapması',
	'NOTIFICATION_TYPE_REPORT'							=> 'Birinin bir mesajı raporlaması',
	'NOTIFICATION_TYPE_REPORT_CLOSED'					=> 'Bir maderatör tarafından bir mesaj üzerindeki raporunuzun kapatılması',
	'NOTIFICATION_TYPE_REPORT_PM'						=> 'Birinin özel bir mesajı raporlaması',
	'NOTIFICATION_TYPE_REPORT_PM_CLOSED'				=> 'Bir maderatör tarafından bir özel mesaj üzerindeki raporunuzun kapatılması',
	'NOTIFICATION_TYPE_TOPIC'							=> 'Birinin abonesi olduğunuz bir forumda bir konu oluşturması',
	'NOTIFICATION_TYPE_ADMIN_ACTIVATE_USER'				=> 'Aktivasyon gereken kullanıcı',

	'NOTIFY_METHOD'					=> 'Bildirim yöntemi',
	'NOTIFY_METHOD_BOTH'			=> 'Both',
	'NOTIFY_METHOD_EMAIL'			=> 'Sadece eposta',
	'NOTIFY_METHOD_EXPLAIN'			=> 'Method for sending messages sent via this board.',
	'NOTIFY_METHOD_IM'				=> 'Jabber only',
	'NOTIFY_ON_PM'					=> 'Notify me on new private messages',
	'NOT_ADDED_FRIENDS_ANONYMOUS'	=> 'You cannot add the anonymous user to your friends list.',
	'NOT_ADDED_FRIENDS_BOTS'		=> 'You cannot add bots to your friends list.',
	'NOT_ADDED_FRIENDS_FOES'		=> 'You cannot add users to your friends list who are on your foes list.',
	'NOT_ADDED_FRIENDS_SELF'		=> 'You cannot add yourself to the friends list.',
	'NOT_ADDED_FOES_MOD_ADMIN'		=> 'You cannot add administrators and moderators to your foes list.',
	'NOT_ADDED_FOES_ANONYMOUS'		=> 'You cannot add the anonymous user to your foes list.',
	'NOT_ADDED_FOES_BOTS'			=> 'You cannot add bots to your foes list.',
	'NOT_ADDED_FOES_FRIENDS'		=> 'You cannot add users to your foes list who are on your friends list.',
	'NOT_ADDED_FOES_SELF'			=> 'You cannot add yourself to the foes list.',
	'NOT_AGREE'						=> 'I do not agree to these terms',
	'NOT_ENOUGH_SPACE_FOLDER'		=> 'The destination folder “%s” seems to be full. The requested action has not been taken.',
	'NOT_MOVED_MESSAGES'			=> array(
		1	=> 'You have %d private message currently on hold because of full folder.',
		2	=> 'You have %d private messages currently on hold because of full folder.',
	),
	'NO_ACTION_MODE'				=> 'No message action specified.',
	'NO_AUTHOR'						=> 'No author defined for this message',
	'NO_AVATAR'						=> 'No avatar selected',
	'NO_AVATAR_CATEGORY'			=> 'None',

	'NO_AUTH_DELETE_MESSAGE'		=> 'You are not authorised to delete private messages.',
	'NO_AUTH_EDIT_MESSAGE'			=> 'You are not authorised to edit private messages.',
	'NO_AUTH_FORWARD_MESSAGE'		=> 'You are not authorised to forward private messages.',
	'NO_AUTH_GROUP_MESSAGE'			=> 'You are not authorised to send private messages to groups.',
	'NO_AUTH_PROFILEINFO'			=> 'You are not authorised to change your profile information.',
	'NO_AUTH_READ_HOLD_MESSAGE'		=> 'You are not authorised to read private messages that are on hold.',
	'NO_AUTH_READ_MESSAGE'			=> 'You are not authorised to read private messages.',
	'NO_AUTH_PRINT_MESSAGE'			=> 'You are not authorised to print private messages.',
	'NO_AUTH_READ_REMOVED_MESSAGE'	=> 'You are not able to read this message because it was removed by the author.',
	'NO_AUTH_SEND_MESSAGE'			=> 'You are not authorised to send private messages.',
	'NO_AUTH_SIGNATURE'				=> 'You are not authorised to define a signature.',

	'NO_BCC_RECIPIENT'			=> 'Yok',
	'NO_BOOKMARKS'				=> 'Yer imleriniz bulunmuyor.',
	'NO_BOOKMARKS_SELECTED'		=> 'Hiçbir yer imi seçmediniz.',
	'NO_EDIT_READ_MESSAGE'		=> 'Private message cannot be edited because it has already been read.',
	'NO_EMAIL_USER'				=> 'The email/username information submitted could not be found.',
	'EMAIL_NOT_UNIQUE'			=> 'Email you specified is used by multiple users. You must specify username as well.',
	'NO_FOES'					=> 'No foes currently defined',
	'NO_FRIENDS'				=> 'No friends currently defined',
	'NO_FRIENDS_OFFLINE'		=> 'No friends offline',
	'NO_FRIENDS_ONLINE'			=> 'No friends online',
	'NO_GROUP_SELECTED'			=> 'No group specified.',
	'NO_IMPORTANT_NEWS'			=> 'No important announcements present.',
	'NO_MESSAGE'				=> 'Private message could not be found.',
	'NO_NEW_FOLDER_NAME'		=> 'You have to specify a new folder name.',
	'NO_NEWER_PM'				=> 'No newer messages.',
	'NO_OLDER_PM'				=> 'No older messages.',
	'NO_PASSWORD_SUPPLIED'		=> 'You cannot login without a password.',
	'NO_RECIPIENT'				=> 'No recipient defined.',
	'NO_RESET_TOKEN'			=> 'You did not provide a password reset token.',
	'NO_RULES_DEFINED'			=> 'No rules defined.',
	'NO_SAVED_DRAFTS'			=> 'No drafts saved.',
	'NO_TO_RECIPIENT'			=> 'None',
	'NO_WATCHED_FORUMS'			=> 'You are not subscribed to any forums.',
	'NO_WATCHED_SELECTED'		=> 'You have not selected any subscribed topics or forums.',
	'NO_WATCHED_TOPICS'			=> 'You are not subscribed to any topics.',

	'PASS_TYPE_ALPHA_EXPLAIN'	=> 'Password must be at least %1$s long, must contain letters in mixed case and must contain numbers.',
	'PASS_TYPE_ANY_EXPLAIN'		=> 'Must be at least %1$s long.',
	'PASS_TYPE_CASE_EXPLAIN'	=> 'Password must be at least %1$s long and must contain letters in mixed case.',
	'PASS_TYPE_SYMBOL_EXPLAIN'	=> 'Password must be at least %1$s long, must contain letters in mixed case, must contain numbers and must contain symbols.',
	'PASSWORD'					=> 'Şifre',
	'PASSWORD_ACTIVATED'		=> 'Yeni şifreniz aktifleştirildi.',
	'PASSWORD_RESET'			=> 'Şifreniz başarıyla sıfırlandı.',
	'PASSWORD_RESET_LINK_SENT'	=> 'If your account exists, a password reset link was sent to your registered email address. If you do not receive an email, it may be because you are banned, your account is not activated, you have requested multiple password resets within a short time frame, or you are not allowed to change your password. Contact an administrator if any of those reasons apply. Also, please check your spam filter.',
	'PERMISSIONS_RESTORED'		=> 'Orijinal izinler başarıyla geri yüklendi.',
	'PERMISSIONS_TRANSFERRED'	=> 'Successfully transferred permissions from <strong>%s</strong>, you are now able to browse the board with this user’s permissions.<br />Please note that admin permissions were not transferred. You are able to revert to your permission set at any time.',
	'PM_DISABLED'				=> 'Bu panoda özel mesajlaşma devre dışı bırakıldı.',
	'PM_FROM'					=> 'Gönderici',
	'PM_FROM_REMOVED_AUTHOR'	=> 'Bu mesaj artık kayıtlı olmayan bir kullanıcı tarafından gönderildi.',
	'PM_ICON'					=> 'ÖM ikon',
	'PM_INBOX'					=> 'Gelen',
	'PM_MARK_ALL_READ'			=> 'Tüm mesajları okundu olarak işaretle',
	'PM_MARK_ALL_READ_SUCCESS'	=> 'All private messages in this folder have been marked read',
	'PM_NO_USERS'				=> 'The requested users to be added do not exist.',
	'PM_OUTBOX'					=> 'Giden',
	'PM_SENTBOX'				=> 'Gönderilen mesajlar',
	'PM_SUBJECT'				=> 'Mesaj başlığı',
	'PM_TO'						=> 'Gönderilen',
	'PM_TOOLS'					=> 'Mesaj araçları',
	'PM_USERS_REMOVED_NO_PERMISSION'	=> 'Some users couldn’t be added as they do not have permission to read private messages.',
	'PM_USERS_REMOVED_NO_PM'	=> 'Some users couldn’t be added as they have disabled private message receipt.',
	'POST_EDIT_PM'				=> 'Mesajı düzenle',
	'POST_FORWARD_PM'			=> 'Mesajı ilet',
	'POST_NEW_PM'				=> 'Mesaj oluştur',
	'POST_PM_LOCKED'			=> 'Özel mesajlaşma kilitlendi.',
	'POST_PM_POST'				=> 'Mesajı alıntıla',
	'POST_QUOTE_PM'				=> 'Mesajı alıntıla',
	'POST_REPLY_PM'				=> 'Mesaja cevap yaz',
	'PRINT_PM'					=> 'Yazıcı görünümü',
	'PREFERENCES_UPDATED'		=> 'Tercihleriniz başarıyla güncellendi.',
	'PROFILE_INFO_NOTICE'		=> 'Bu bilgilerin diğer üyeler tarafından görüntülenebileceğini lütfen unutmayın. Kişisel bilgilerinizi eklerken dikkatli olun. * ile işaretlenmiş alanların doldurulması zorunludur.',
	'PROFILE_UPDATED'			=> 'Profiliniz başarıyla güncellendi.',
	'PROFILE_AUTOLOGIN_KEYS'	=> '"Beni Hatırla" girişleri panoyu ziyaret ettiğinizde otomatik olarak oturum açmanızı sağlar. Çıkış yaparsanız giriş anahtarı yalnızca çıkış yapmak için kullandığınız bilgisayarda silinir. Burada, bu siteye erişmek için kullandığınız diğer bilgisayarlarda oluşturulan giriş anahtarlarını görüntüleyebilirsiniz.',
	'PROFILE_NO_AUTOLOGIN_KEYS'	=> 'Kaydedilmiş "Beni hatırla" giriş anahtarı yok.',

	'RECIPIENT'							=> 'Alıcı',
	'RECIPIENTS'						=> 'Alıcılar',
	'REGISTRATION'						=> 'Kayıt',
	'OAUTH_REGISTRATION'				=> 'Harici hizmetleri kullanarak kayıt',
	'RELEASE_MESSAGES'					=> '%sBeklemedeki tüm mesajları serbest bırakın%s… Yeterli alan sağlanırsa bunlar uygun klasöre yeniden sıralanacaktır.',
	'REMOVE_ADDRESS'					=> 'Adresi kaldır',
	'REMOVE_SELECTED_BOOKMARKS'			=> 'Seçili yer imlerini kaldır',
	'REMOVE_SELECTED_BOOKMARKS_CONFIRM'	=> 'Seçili tüm yer imlerini silmek istediğinize emin misiniz?',
	'REMOVE_BOOKMARK_MARKED'			=> 'İşaretli yer imlerini kaldır',
	'REMOVE_FOLDER'						=> 'Klasörü kaldır',
	'REMOVE_FOLDER_CONFIRM'				=> 'Bu klasörü kaldırmak istediğinize emin misiniz?',
	'RENAME'							=> 'Yeniden adlandır',
	'RENAME_FOLDER'						=> 'Klasörü yeniden adlandır',
	'REPLIED_MESSAGE'					=> 'Mesaj cevaplandı',
	'REPLY_TO_ALL'						=> 'Gönderene ve tüm alıcılara cevap yaz',
	'REPORT_PM'							=> 'Özel mesajı raporla',
	'RESET_PASSWORD'					=> 'Şifreyi sıfırla',
	'RESET_TOKEN_EXPIRED_OR_INVALID'	=> 'Sağladığınız şifre sıfırlama belirteci geçersiz veya süresi dolmuş.',
	'RESIGN_SELECTED'					=> 'Resign selected',
	'RETURN_FOLDER'						=> '%1$sÖnceki klasöre dön%2$s',
	'RETURN_UCP'						=> '%sKullanıcı Kontrol Paneline dön%s',
	'RULE_ADDED'						=> 'Kural başarıyla eklendi.',
	'RULE_ALREADY_DEFINED'				=> 'Bu kural daha önce tanımlanmıştı.',
	'RULE_DELETED'						=> 'Kural başarıyla kaldırıldı.',
	'RULE_LIMIT_REACHED'				=> 'Daha fazla ÖM kuralı ekleyemezsiniz. Maksimum kural sayısına ulaştınız.',
	'RULE_NOT_DEFINED'					=> 'Kural doğru şekilde belirtilmedi.',
	'RULE_REMOVED_MESSAGES'				=> array(
		1	=> '%d özel mesaj, özel mesaj filtreleri nedeniyle kaldırıldı.',
		2	=> '%d özel mesaj, özel mesaj filtreleri nedeniyle kaldırıldı.',
	),

	'SAME_PASSWORD_ERROR'		=> 'Girdiğiniz yeni şifre mevcut şifrenizle aynıdır.',
	'SEARCH_YOUR_POSTS'			=> 'Mesajlarını görüntüle',
	'SENT_AT'					=> 'Gönderildi',			// Used before dates in private messages
	'SHOW_EMAIL'				=> 'Kullanıcılar benimle eposta yoluyla iletişime geçebilir',
	'SIGNATURE_EXPLAIN'			=> 'This is a block of text that can be added to posts you make. There is a %d character limit.',
	'SIGNATURE_PREVIEW'			=> 'Your signature will appear like this in posts',
	'SIGNATURE_TOO_LONG'		=> 'Your signature is too long.',
	'SELECT_CURRENT_TIME'		=> 'Geçerli saati seçin',
	'SELECT_TIMEZONE'			=> 'Zaman dilimi seç',
	'SORT'						=> 'Sort',
	'SORT_COMMENT'				=> 'File comment',
	'SORT_DOWNLOADS'			=> 'Downloads',
	'SORT_EXTENSION'			=> 'Extension',
	'SORT_FILENAME'				=> 'Dosya adı',
	'SORT_POST_TIME'			=> 'Post time',
	'SORT_SIZE'					=> 'Dosya boyutu',

	'TIMEZONE'					=> 'Zaman dilimi',
	'TIMEZONE_DATE_SUGGESTION'	=> 'Öneri: %s',
	'TIMEZONE_INVALID'			=> 'Seçtiğiniz saat dilimi geçersiz.',
	'TO'						=> 'Alıcı',
	'TO_MASS'					=> 'Alıcılar',
	'TO_ADD'					=> 'Alıcı ekle',
	'TO_ADD_MASS'				=> 'Alıcılar ekle',
	'TO_ADD_GROUPS'				=> 'Grupları ekle',
	'TOO_MANY_RECIPIENTS'		=> 'Çok fazla alıcıya özel mesaj göndermeye çalıştınız.',
	'TOO_MANY_REGISTERS'		=> 'Bu oturum için maksimum kayıt denemesi sayısını aştınız. Lütfen daha sonra tekrar deneyiniz.',

	'UCP'						=> 'Kullanıcı Kontrol Paneli',
	'UCP_ACTIVATE'				=> 'Hesabı aktifleştir',
	'UCP_ADMIN_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. The administrator will review your account and if approved you will receive an email at the address you specified.',
	'UCP_ATTACHMENTS'			=> 'Ekler',
	'UCP_AUTH_LINK'				=> 'External accounts',
	'UCP_AUTH_LINK_ASK'			=> 'You currently have no account associated with this external service. Click the button below to link your board account to an account with this external service.',
	'UCP_AUTH_LINK_ID'			=> 'Unique identifier',
	'UCP_AUTH_LINK_LINK'		=> 'Link',
	'UCP_AUTH_LINK_MANAGE'		=> 'Manage external account associations',
	'UCP_AUTH_LINK_NOT_SUPPORTED'	=> 'Linking board accounts to external services is not supported by this board’s current authentication method.',
	'UCP_AUTH_LINK_TITLE'		=> 'Manage your external account associations',
	'UCP_AUTH_LINK_UNLINK'		=> 'Unlink',
	'UCP_COPPA_BEFORE'			=> 'Before %s',
	'UCP_COPPA_ON_AFTER'		=> 'On or after %s',
	'UCP_EMAIL_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. You will receive an email at the address you provide that contains an account activation link.',
	'UCP_JABBER'				=> 'Jabber address',
	'UCP_LOGIN_LINK'			=> 'Set up an external account association',

	'UCP_MAIN'					=> 'Genel Bakış',
	'UCP_MAIN_ATTACHMENTS'		=> 'Ekleri yönet',
	'UCP_MAIN_BOOKMARKS'		=> 'Yer imlerini yönet',
	'UCP_MAIN_DRAFTS'			=> 'Taslakları yönet',
	'UCP_MAIN_FRONT'			=> 'Ön sayfa',
	'UCP_MAIN_SUBSCRIBED'		=> 'Abonelikleri Yönet',

	'UCP_NO_ATTACHMENTS'		=> 'Hiçbir dosya göndermediniz.',

	'UCP_NOTIFICATION_LIST'				=> 'Bildirimleri yönet',
	'UCP_NOTIFICATION_LIST_EXPLAIN'		=> 'Burada tüm geçmiş bildirimleri görüntüleyebilirsiniz.',
	'UCP_NOTIFICATION_OPTIONS'			=> 'Bildirim seçeneklerini düzenle',
	'UCP_NOTIFICATION_OPTIONS_EXPLAIN'	=> 'Burada pano için tercih ettiğiniz bildirim yöntemlerini ayarlayabilirsiniz.',

	'UCP_PREFS'					=> 'Pano tercihleri',
	'UCP_PREFS_PERSONAL'		=> 'Genel ayarları düzenle',
	'UCP_PREFS_POST'			=> 'Gönderim varsayılanlarını düzenle',
	'UCP_PREFS_VIEW'			=> 'Görüntüleme seçeneklerini düzenle',

	'UCP_PM'					=> 'Özel mesajlar',
	'UCP_PM_COMPOSE'			=> 'Mesaj oluştur',
	'UCP_PM_DRAFTS'				=> 'ÖM taslaklarını yönet',
	'UCP_PM_OPTIONS'			=> 'Kurallar, klasörler &amp; ayarlar',
	'UCP_PM_UNREAD'				=> 'Okunmamış mesajlar',
	'UCP_PM_VIEW'				=> 'Mesajı görüntüle',

	'UCP_PROFILE'				=> 'Profil',
	'UCP_PROFILE_AVATAR'		=> 'Avatarı düzenle',
	'UCP_PROFILE_PROFILE_INFO'	=> 'Profili düzenle',
	'UCP_PROFILE_REG_DETAILS'	=> 'Hesap ayarlarını düzenle',
	'UCP_PROFILE_SIGNATURE'		=> 'İmzayı düzenle',
	'UCP_PROFILE_AUTOLOGIN_KEYS'=> '“Beni hatırla” giriş anahtarlarını yönet',

	'UCP_USERGROUPS'			=> 'Kullanıcı grupları',
	'UCP_USERGROUPS_MEMBER'		=> 'Üyelikleri düzenle',
	'UCP_USERGROUPS_MANAGE'		=> 'Grupları yönet',

	'UCP_PASSWORD_RESET_DISABLED'	=> 'Şifre sıfırlama fonksiyonu devre dışı bırakıldı. Hesabınıza erişme konusunda yardıma ihtiyacınız varsa lütfen %sPano Yöneticisi%s ile iletişime geçin',
	'UCP_REGISTER_DISABLE'			=> 'Yeni bir hesap oluşturmak şu anda mümkün değil.',
	'UCP_RESEND'					=> 'Aktivasyon epostası gönder',
	'UCP_WELCOME'					=> 'Kullanıcı Kontrol Paneline hoş geldiniz. Buradan profilinizi, tercihlerinizi, abone olunan forum ve konuları izleyebilir, görüntüleyebilir ve güncelleyebilirsiniz. Ayrıca diğer kullanıcılara da mesaj gönderebilirsiniz (eğer izin veriliyorsa). Lütfen devam etmeden önce duyuruları okuduğunuza emin olun.',
	'UCP_ZEBRA'						=> 'Arkadaşlar &amp; Engelliler',
	'UCP_ZEBRA_FOES'				=> 'Engellileri yönet',
	'UCP_ZEBRA_FRIENDS'				=> 'Arkadaşları yönet',
	'UNDISCLOSED_RECIPIENT'			=> 'Gösterilmeyen alıcı',
	'UNKNOWN_FOLDER'				=> 'Bilinmeyen klasör',
	'UNWATCH_MARKED'				=> 'İşaretlileri takipten çık',
	'UPLOAD_AVATAR_FILE'			=> 'Makinenizden yükleyin',
	'UPLOAD_AVATAR_URL'				=> 'Bir URL üzerinden yükle',
	'UPLOAD_AVATAR_URL_EXPLAIN'		=> 'Enter the URL of the location containing the image. The image will be copied to this site.',
	'USERNAME_ALPHA_ONLY_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only alphanumeric characters.',
	'USERNAME_ALPHA_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use alphanumeric, space or -+_[] characters.',
	'USERNAME_ASCII_EXPLAIN'		=> 'Username must be between %1$s and %2$s long and use only ASCII characters, so no special symbols.',
	'USERNAME_LETTER_NUM_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only letter or number characters.',
	'USERNAME_LETTER_NUM_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use letter, number, space or -+_[] characters.',
	'USERNAME_CHARS_ANY_EXPLAIN'	=> 'Length must be between %1$s and %2$s.',
	'USERNAME_TAKEN_USERNAME'		=> 'The username you entered is already in use, please select an alternative.',
	'USERNAME_DISALLOWED_USERNAME'	=> 'The username you entered has been disallowed or contains a disallowed word. Please choose a different name.',
	'USER_NOT_FOUND_OR_INACTIVE'	=> 'The usernames you specified could either not be found or are not activated users.',

	'VIEW_AVATARS'				=> 'Avatarları görüntüle',
	'VIEW_EDIT'					=> 'Görüntüle/Düzenle',
	'VIEW_FLASH'				=> 'Flash animasyonlarını görüntüle',
	'VIEW_IMAGES'				=> 'Mesajlardaki resimleri görüntüle',
	'VIEW_NEXT_HISTORY'			=> 'Next PM in history',
	'VIEW_NEXT_PM'				=> 'Sonraki ÖM',
	'VIEW_PM'					=> 'Mesajı görüntüle',
	'VIEW_PM_INFO'				=> 'Mesaj ayrıntıları',
	'VIEW_PM_MESSAGES'			=> array(
		1	=> '%d mesaj',
		2	=> '%d mesaj',
	),
	'VIEW_PREVIOUS_HISTORY'		=> 'Geçmiş önceki ÖM',
	'VIEW_PREVIOUS_PM'			=> 'Önceki ÖM',
	'VIEW_PROFILE'				=> 'Profilleri görüntüle',
	'VIEW_SIGS'					=> 'İmzaları görüntüle',
	'VIEW_SMILIES'				=> 'İfadeleri resim olarak görüntüle',
	'VIEW_TOPICS_DAYS'			=> 'Önceki günlerin konularının görüntülenmesi',
	'VIEW_TOPICS_DIR'			=> 'Konu sıralama yönü görüntülenmesi',
	'VIEW_TOPICS_KEY'			=> 'Konu sıralamasını şuna göre görüntüle',
	'VIEW_POSTS_DAYS'			=> 'Önceki günlerin mesajlarının görüntülenmesi',
	'VIEW_POSTS_DIR'			=> 'Mesaj sıralama yönü görüntülenmesi',
	'VIEW_POSTS_KEY'			=> 'Mesaj sıralamasını şuna göre görüntüle',

	'WATCHED_EXPLAIN'			=> 'Aşağıda abone olduğunuz forumların ve konuların bir listesi bulunmaktadır. Her ikisinde de yeni gönderiler konusunda bilgilendirileceksiniz. Abonelikten çıkmak için forumu veya konuyu işaretleyin ve ardından <em>İşaretlileri takipten çık</em> düğmesine basın.',
	'WATCHED_FORUMS'			=> 'izlenen forumlar',
	'WATCHED_TOPICS'			=> 'İzlenen konular',
	'WRONG_ACTIVATION'			=> 'Belirttiğiniz aktivasyon anahtarı veritabanındaki hiçbir aktivasyon anahtarıyla eşleşmiyor.',

	'YOUR_DETAILS'				=> 'Faaliyetiniz',
	'YOUR_FOES'					=> 'Engellilerin',
	'YOUR_FOES_EXPLAIN'			=> 'Kullanıcı adlarını kaldırmak için bunları seçin ve göndere tıklayın.',
	'YOUR_FRIENDS'				=> 'Arkadaşların',
	'YOUR_FRIENDS_EXPLAIN'		=> 'Kullanıcı adlarını kaldırmak için bunları seçin ve göndere tıklayın.',
	'YOUR_WARNINGS'				=> 'Uyarı seviyeniz',

	'PM_ACTION' => array(
		'PLACE_INTO_FOLDER'	=> 'Klasöre yerleştir',
		'MARK_AS_READ'		=> 'Okundu olarak işaretle',
		'MARK_AS_IMPORTANT'	=> 'Mesajı işaretle',
		'DELETE_MESSAGE'	=> 'Mesajı sil',
	),
	'PM_CHECK' => array(
		'SUBJECT'	=> 'Konu',
		'SENDER'	=> 'Gönderen',
		'MESSAGE'	=> 'Mesaj',
		'STATUS'	=> 'Mesaj statüsü',
		'TO'		=> 'Gönderilen',
	),
	'PM_RULE' => array(
		'IS_LIKE'		=> 'gibiyse',
		'IS_NOT_LIKE'	=> 'gibi değilse',
		'IS'			=> 'şuysa',
		'IS_NOT'		=> 'şu değilse',
		'BEGINS_WITH'	=> 'şununla başlıyorsa',
		'ENDS_WITH'		=> 'şununla bitiyorsa',
		'IS_FRIEND'		=> 'arkadaş ise',
		'IS_FOE'		=> 'engellilerde ise',
		'IS_USER'		=> 'kullanıcı ise',
		'IS_GROUP'		=> 'şu kullanıcı grubunun içindeyse',
		'ANSWERED'		=> 'cevaplandıysa',
		'FORWARDED'		=> 'iletildiyse',
		'TO_GROUP'		=> 'benim varsayılan grubuma ise',
		'TO_ME'			=> 'banaysa',
	),

	'GROUPS_EXPLAIN'	=> 'Kullanıcı grupları pano yöneticilerinin kullanıcıları daha iyi yönetmesini sağlar. Varsayılan olarak belirli bir gruba yerleştirileceksiniz, bu varsayılan grubunuzdur. Bu grup diğer kullanıcılara nasıl görünebileceğinizi tanımlar, örneğin kullanıcı adınızın rengi, avatarınız, rütbeniz vb. Yöneticinin izin verip vermemesine bağlı olarak varsayılan grubunuzu değiştirmenize izin verilebilir. Ayrıca başka gruplara yerleştirilebilir veya katılmanıza izin verilebilir. Bazı gruplar içeriği görüntülemeniz veya diğer alanlardaki yeteneklerinizi artırmanız için size ek izinler verebilir.',
	'GROUP_LEADER'		=> 'Liderlikler',
	'GROUP_MEMBER'		=> 'Üyelikler',
	'GROUP_PENDING'		=> 'Bekleyen üyelikler',
	'GROUP_NONMEMBER'	=> 'Olunmayan üyelikler',
	'GROUP_DETAILS'		=> 'Grup ayrıntıları',

	'NO_LEADER'		=> 'Grup liderliği yok',
	'NO_MEMBER'		=> 'Grup üyeliği yok',
	'NO_PENDING'	=> 'Bekleyen üyelik yok',
	'NO_NONMEMBER'	=> 'Üyeliği olmayan gruplar yok',
));
