<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

// Privacy policy and T&C
$lang = array_merge($lang, array(
	'TERMS_OF_USE_CONTENT'	=> 'By accessing “%1$s” (hereinafter “we”, “us”, “our”, “%1$s”, “%2$s”), you agree to be legally bound by the following terms. If you do not agree to be legally bound by all of the following terms then please do not access and/or use “%1$s”. We may change these at any time and we’ll do our utmost in informing you, though it would be prudent to review this regularly yourself as your continued usage of “%1$s” after changes mean you agree to be legally bound by these terms as they are updated and/or amended.
	<br><br>
	Our forums are powered by phpBB (hereinafter “they”, “them”, “their”, “phpBB software”, “www.phpbb.com”, “phpBB Limited”, “phpBB Teams”) which is a bulletin board solution released under the “<a href="http://opensource.org/licenses/gpl-2.0.php">GNU General Public License v2</a>” (hereinafter “GPL”) and can be downloaded from <a href="https://www.phpbb.com/">www.phpbb.com</a>. The phpBB software only facilitates internet based discussions; phpBB Limited is not responsible for what we allow and/or disallow as permissible content and/or conduct. For further information about phpBB, please see: <a href="https://www.phpbb.com/">https://www.phpbb.com/</a>.
	<br><br>
	You agree not to post any abusive, obscene, vulgar, slanderous, hateful, threatening, sexually-orientated or any other material that may violate any laws be it of your country, the country where “%1$s” is hosted or International Law. Doing so may lead to you being immediately and permanently banned, with notification of your Internet Service Provider if deemed required by us. The IP address of all posts are recorded to aid in enforcing these conditions. You agree that “%1$s” have the right to remove, edit, move or close any topic at any time should we see fit. As a user you agree to any information you have entered to being stored in a database. While this information will not be disclosed to any third party without your consent, neither “%1$s” nor phpBB shall be held responsible for any hacking attempt that may lead to the data being compromised.
	',

	'PRIVACY_POLICY'		=> 'This policy explains in detail how “%1$s” along with its affiliated companies (hereinafter “we”, “us”, “our”, “%1$s”, “%2$s”) and phpBB (hereinafter “they”, “them”, “their”, “phpBB software”, “www.phpbb.com”, “phpBB Limited”, “phpBB Teams”) use any information collected during any session of usage by you (hereinafter “your information”).
	<br><br>
	Your information is collected via two ways. Firstly, by browsing “%1$s” will cause the phpBB software to create a number of cookies, which are small text files that are downloaded on to your computer’s web browser temporary files. The first two cookies just contain a user identifier (hereinafter “user-id”) and an anonymous session identifier (hereinafter “session-id”), automatically assigned to you by the phpBB software. A third cookie will be created once you have browsed topics within “%1$s” and is used to store which topics have been read, thereby improving your user experience.
	<br><br>
	We may also create cookies external to the phpBB software whilst browsing “%1$s”, though these are outside the scope of this document which is intended to only cover the pages created by the phpBB software. The second way in which we collect your information is by what you submit to us. This can be, and is not limited to: posting as an anonymous user (hereinafter “anonymous posts”), registering on “%1$s” (hereinafter “your account”) and posts submitted by you after registration and whilst logged in (hereinafter “your posts”).
	<br><br>
	Your account will at a bare minimum contain a uniquely identifiable name (hereinafter “your user name”), a personal password used for logging into your account (hereinafter “your password”) and a personal, valid email address (hereinafter “your email”). Your information for your account at “%1$s” is protected by data-protection laws applicable in the country that hosts us. Any information beyond your user name, your password, and your email address required by “%1$s” during the registration process is either mandatory or optional, at the discretion of “%1$s”. In all cases, you have the option of what information in your account is publicly displayed. Furthermore, within your account, you have the option to opt-in or opt-out of automatically generated emails from the phpBB software.
	<br><br>
	Your password is ciphered (a one-way hash) so that it is secure. However, it is recommended that you do not reuse the same password across a number of different websites. Your password is the means of accessing your account at “%1$s”, so please guard it carefully and under no circumstance will anyone affiliated with “%1$s”, phpBB or another 3rd party, legitimately ask you for your password. Should you forget your password for your account, you can use the “I forgot my password” feature provided by the phpBB software. This process will ask you to submit your user name and your email, then the phpBB software will generate a new password to reclaim your account.
	',
));

// Common language entries
$lang = array_merge($lang, array(
	'ACCOUNT_ACTIVE'				=> 'Hesabınız şimdi aktifleştirildi. Kayıt olduğunuz için teşekkürler.',
	'ACCOUNT_ACTIVE_ADMIN'			=> 'Hesap şimdi aktifleştirildi.',
	'ACCOUNT_ACTIVE_PROFILE'		=> 'Hesabınız şimdi başarıyla yeniden aktifleştirildi.',
	'ACCOUNT_ADDED'					=> 'Kayıt olduğunuz için teşekkürler, hesabınız oluşturuldu.',
	'ACCOUNT_COPPA'					=> 'Hesabınız oluşturuldu ancak onaylanması gerekiyor. Ayrıntılar için lütfen epostanızı kontrol edin.',
	'ACCOUNT_EMAIL_CHANGED'			=> 'Hesabın güncellendi. Ancak bu mesaj panosu, eposta değişikliklerinde hesabın yeniden aktifleştirilmesini gerektirir. Belirttiğiniz yeni eposta adresine bir aktivasyon anahtarı gönderildi. Daha fazla bilgi için lütfen epostanızı kontrol edin.',
	'ACCOUNT_EMAIL_CHANGED_ADMIN'	=> 'Hesabın güncellendi. Ancak bu mesaj panosu, eposta değişikliklerinde hesabın yöneticiler tarafından yeniden aktifleştirilmesini gerektirir. Onlara bir eposta gönderildi ve hesabınız yeniden aktifleştirildiğinde size bilgi verilecek.',
	'ACCOUNT_INACTIVE'				=> 'Hesabınız oluşturuldu. Ancak bu mesaj panosu hesap aktivasyonunu gerektirir. Verdiğiniz eposta adresine bir aktivasyon anahtarı gönderildi. Daha fazla bilgi için lütfen epostanızı kontrol edin ve ayrıca istenmeyen posta kutunuzu da kontrol ettiğinizden emin olun. Eposta sağlayıcınıza bağlı olarak epostayı almanız biraz zaman alabilir.',
	'ACCOUNT_INACTIVE_ADMIN'		=> 'Hesabınız oluşturuldu. Ancak bu mesaj panosu yönetici grubu tarafından hesabın etkinleştirilmesini gerektirir. Onlara bir eposta gönderildi ve hesabınız aktifleştirildiğinde size bilgi verilecek.',
	'ACTIVATION_EMAIL_SENT'			=> 'Aktivasyon epostası eposta adresinize gönderildi.',
	'ACTIVATION_EMAIL_SENT_ADMIN'	=> 'Aktivasyon epostası yöneticilerin eposta adreslerine gönderildi.',
	'ADD'							=> 'Ekle',
	'ADD_BCC'						=> 'Ekle [BCC]',
	'ADD_FOES'						=> 'Yeni engelliler ekle',
	'ADD_FOES_EXPLAIN'				=> 'Farklı bir satıra birden fazla kullanıcı adı girebilirsiniz.',
	'ADD_FOLDER'					=> 'Klasör ekle',
	'ADD_FRIENDS'					=> 'Yeni arkadaşlar ekle',
	'ADD_FRIENDS_EXPLAIN'			=> 'Farklı bir satıra birden fazla kullanıcı adı girebilirsiniz.',
	'ADD_NEW_RULE'					=> 'Yeni kural ekle',
	'ADD_RULE'						=> 'Kural ekle',
	'ADD_TO'						=> 'Ekle [Alıcı]',
	'ADD_USERS_UCP_EXPLAIN'			=> 'Here you can add new users to the group. You may select whether this group becomes the new default for the selected users. Please enter each username on a separate line.',
	'ADMIN_EMAIL'					=> 'Yöneticiler beni eposta ile bilgilendirebilir',
	'AGREE'							=> 'Bu şartları kabul ediyorum',
	'ALLOW_PM'						=> 'Kullanıcıların size özel mesaj göndermesine izin verin',
	'ALLOW_PM_EXPLAIN'				=> 'Yöneticilerin ve moderatörlerin size her zaman mesaj gönderebileceğini unutmayın.',
	'ALREADY_ACTIVATED'				=> 'Hesabınızı zaten aktif hale getirdiniz.',
	'ATTACHMENTS_EXPLAIN'			=> 'Bu panoya gönderdiğiniz gönderilerdeki eklerin listesidir.',
	'ATTACHMENTS_DELETED'			=> 'Ekler başarıyla silindi.',
	'ATTACHMENT_DELETED'			=> 'Ek başarıyla silindi.',
	'ATTACHMENT_LOCKED'				=> 'Bu konu kilitlendi, ek silemezsiniz.',
	'AUTOLOGIN_SESSION_KEYS_DELETED'=> 'Seçilen "Beni hatırla" giriş anahtarları başarıyla silindi.',
	'AVATAR_CATEGORY'				=> 'Kategori',
	'AVATAR_DRIVER_GRAVATAR_TITLE'	=> 'Gravatar',
	'AVATAR_DRIVER_GRAVATAR_EXPLAIN'=> 'Gravatar birden fazla web sitesinde aynı avatarı kullanmanıza olanak tanıyan bir hizmettir. Daha fazla bilgi için <a href="http://www.gravatar.com/">Gravatar</a> sitesini ziyaret edin.',
	'AVATAR_DRIVER_LOCAL_TITLE'		=> 'Galeri avatarı',
	'AVATAR_DRIVER_LOCAL_EXPLAIN'	=> 'Avatarınızı yerel olarak mevcut olan avatarlar arasından seçebilirsiniz.',
	'AVATAR_DRIVER_REMOTE_TITLE'	=> 'Uzak avatar',
	'AVATAR_DRIVER_REMOTE_EXPLAIN'	=> 'Başka bir web sitesinden avatar resimlerine bağlantı verin.',
	'AVATAR_DRIVER_UPLOAD_TITLE'	=> 'Avatar yükle',
	'AVATAR_DRIVER_UPLOAD_EXPLAIN'	=> 'Kendi özel avatarını yükle',
	'AVATAR_EXPLAIN'				=> 'Maksimum boyutlar; genişlik: %1$s, yükseklik: %2$s, dosya boyutu: %3$.2f KiB.',
	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'Maksimum boyutlar; genişlik: %1$s, yükseklik: %2$s.',
	'AVATAR_FEATURES_DISABLED'		=> 'Avatar işlevi şu anda devre dışı.',
	'AVATAR_GALLERY'				=> 'Yerel galeri',
	'AVATAR_GENERAL_UPLOAD_ERROR'	=> 'Avatar yüklenemedi %s.',
	'AVATAR_NOT_ALLOWED'			=> 'Avatarlara izin verilmediğinden avatarınız görüntülenemiyor.',
	'AVATAR_PAGE'					=> 'Sayfa',
	'AVATAR_SELECT'					=> 'Avatarını seç',
	'AVATAR_TYPE'					=> 'Avatar türü',
	'AVATAR_TYPE_NOT_ALLOWED'		=> 'Mevcut avatarınız türüne izin verilmediğinden görüntülenemiyor.',

	'BACK_TO_DRAFTS'			=> 'Kaydedilen taslaklara dön',
	'BACK_TO_LOGIN'				=> 'Giriş ekranına dön',
	'BIRTHDAY'					=> 'Doğum günü',
	'BIRTHDAY_EXPLAIN'			=> 'Bir yıl ayarlamak doğum gününüz olduğunda yaşınızı listeleyecektir.',
	'BOARD_DATE_FORMAT'			=> 'Tarih formatım',
	'BOARD_DATE_FORMAT_EXPLAIN'	=> 'Söz dizimi PHP <a href="https://www.php.net/manual/datetime.format.php">tarih fonksiyonları</a> ile aynı formatı kullanır.',
	'BOARD_LANGUAGE'			=> 'Dilim',
	'BOARD_STYLE'				=> 'Pano stilim',
	'BOARD_TIMEZONE'			=> 'Saat dilimim',
	'BOOKMARKS'					=> 'Yer imleri',
	'BOOKMARKS_EXPLAIN'			=> 'İleride başvurmak üzere konuları yer imlerinize ekleyebilirsiniz. Silmek istediğiniz herhangi bir yer iminin onay kutusunu seçin ve ardından <em>İşaretli yer imlerini kaldır</em> butonuna basın.',
	'BOOKMARKS_DISABLED'		=> 'Yer imleri bu panoda devre dışı bırakıldı',
	'BOOKMARKS_REMOVED'			=> 'Yer imleri başarıyla kaldırıldı.',

	'CANNOT_EDIT_MESSAGE_TIME'	=> 'Artık bu mesajı düzenleyemez veya silemezsiniz.',
	'CANNOT_MOVE_TO_SAME_FOLDER'=> 'Mesajlar kaldırmak istediğiniz klasöre taşınamaz.',
	'CANNOT_MOVE_FROM_SPECIAL'	=> 'Mesajlar giden kutusundan taşınamaz.',
	'CANNOT_RENAME_FOLDER'		=> 'Bu klasör yeniden adlandırılamaz.',
	'CANNOT_REMOVE_FOLDER'		=> 'Bu klasör kaldırılamaz.',
	'CHANGE_DEFAULT_GROUP'		=> 'Varsayılan grubu değiştir',
	'CHANGE_PASSWORD'			=> 'Şifreyi değiştir',
	'CLICK_GOTO_FOLDER'			=> '%1$sGo to your “%3$s” folder%2$s',
	'CLICK_RETURN_FOLDER'		=> '%1$sReturn to your “%3$s” folder%2$s',
	'CONFIRMATION'				=> 'Kayıt doğrulaması',
	'CONFIRM_CHANGES'			=> 'Değişiklikleri onayla',
	'CONFIRM_EXPLAIN'			=> 'To prevent automated registrations the board requires you to enter a confirmation code. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.',
	'VC_REFRESH'				=> 'Doğrulama kodunu yenile',
	'VC_REFRESH_EXPLAIN'		=> 'Kodu okuyamıyorsanız butonuna tıklayarak yeni bir kod talep edebilirsiniz.',

	'CONFIRM_PASSWORD'			=> 'Şifreyi onayla',
	'CONFIRM_PASSWORD_EXPLAIN'	=> 'You only need to confirm your password if you changed it above.',
	'COPPA_BIRTHDAY'			=> 'To continue with the registration procedure please tell us when you were born.',
	'COPPA_COMPLIANCE'			=> 'COPPA compliance',
	'COPPA_EXPLAIN'				=> 'Please note that clicking submit will create your account. However it cannot be activated until a parent or guardian approves your registration. You will be emailed a copy of the necessary form with details of where to send it.',
	'CREATE_FOLDER'				=> 'Klasör ekle…',
	'CURRENT_IMAGE'				=> 'Mevcut resim',
	'CURRENT_PASSWORD'			=> 'Mevcut şifre',
	'CURRENT_PASSWORD_EXPLAIN'	=> 'You must enter your current password if you wish to alter your email address or username.',
	'CURRENT_CHANGE_PASSWORD_EXPLAIN' => 'To change your password, your email address, or your username, you must enter your current password.',
	'CUR_PASSWORD_EMPTY'		=> 'Mevcut şifrenizi girmediniz.',
	'CUR_PASSWORD_ERROR'		=> 'Mevcut şifrenizi yanlış girdiniz.',
	'CUSTOM_DATEFORMAT'			=> 'Özel…',

	'DEFAULT_ACTION'			=> 'Varsayilan eylem',
	'DEFAULT_ACTION_EXPLAIN'	=> 'Yukarıdakilerin hiç biri uygulanabilir değilse bu eylem tetiklenecek.',
	'DEFAULT_ADD_SIG'			=> 'Varsayılan olarak imzamı ekle',
	'DEFAULT_BBCODE'			=> 'Varayılan olarak BBCode etkinleştir',
	'DEFAULT_NOTIFY'			=> 'Varsayılan olarak cevaplar üzerine beni bilgilendir',
	'DEFAULT_SMILIES'			=> 'Varsayılan olarak ifadeleri etkinleştir',
	'DEFINED_RULES'				=> 'Tanımlanmış kurallar',
	'DELETED_TOPIC'				=> 'Konu kaldırıldı.',
	'DELETE_ATTACHMENT'			=> 'Ek sil',
	'DELETE_ATTACHMENTS'		=> 'Ekleri sil',
	'DELETE_ATTACHMENT_CONFIRM'	=> 'Bu eki silmek istediğinize emin misiniz?',
	'DELETE_ATTACHMENTS_CONFIRM'=> 'Bu ekleri silmek istediğinize emin misiniz?',
	'DELETE_AVATAR'				=> 'Resmi sil',
	'DELETE_COOKIES_CONFIRM'	=> 'Bu panonun ayarladığı tüm çerezleri silmek istediğinize emin misiniz?',
	'DELETE_MARKED_PM'			=> 'İşaretli mesajları sil',
	'DELETE_MARKED_PM_CONFIRM'	=> 'Tüm işaretli mesajları silmek istediğinize emin misiniz?',
	'DELETE_OLDEST_MESSAGES'	=> 'Eski mesajları sil',
	'DELETE_MESSAGE'			=> 'Mesajı sil',
	'DELETE_MESSAGE_CONFIRM'	=> 'Bu özel mesajı silmek istediğinize emin misiniz?',
	'DELETE_MESSAGES_IN_FOLDER'	=> 'Kaldırılan klasördeki tüm mesajları sil',
	'DELETE_RULE'				=> 'Kuralı sil',
	'DELETE_RULE_CONFIRM'		=> 'Bu kuralı silmek istediğinize emin misiniz?',
	'DEMOTE_SELECTED'			=> 'Demote selected',
	'DISABLE_CENSORS'			=> 'Enable word censoring',
	'DISPLAY_GALLERY'			=> 'Display gallery',
	'DOWNLOADS'					=> 'İndirmeler',
	'DRAFTS_DELETED'			=> 'Tüm seçili taslaklar başarıyla silindi.',
	'DRAFTS_EXPLAIN'			=> 'Buradan kaydettiğiniz taslakları görüntüleyebilir, düzenleyebilir ve silebilirsiniz.',
	'DRAFT_UPDATED'				=> 'Taslak başarıyla güncellendi.',

	'EDIT_DRAFT_EXPLAIN'		=> 'Here you are able to edit your draft. Drafts do not contain attachment and poll information.',
	'EMAIL_BANNED_EMAIL'		=> 'The email address you entered is not allowed to be used.',
	'EMAIL_REMIND'				=> 'This must be the email address associated with your account. If you have not changed this via your user control panel then it is the email address you registered your account with.',
	'EMAIL_TAKEN_EMAIL'			=> 'The entered email address is already in use.',
	'EMPTY_DRAFT'				=> 'You must enter a message to submit your changes.',
	'EMPTY_DRAFT_TITLE'			=> 'You must enter a draft title.',
	'EXPORT_AS_XML'				=> 'Export as XML',
	'EXPORT_AS_CSV'				=> 'Export as CSV',
	'EXPORT_AS_CSV_EXCEL'		=> 'Export as CSV (Excel)',
	'EXPORT_AS_TXT'				=> 'Export as TXT',
	'EXPORT_AS_MSG'				=> 'Export as MSG',
	'EXPORT_FOLDER'				=> 'Export this view',

	'FIELD_REQUIRED'					=> 'The field “%s” must be completed.',
	'FIELD_TOO_SHORT'					=> array(
		1	=> 'The field “%2$s” is too short, a minimum of %1$d character is required.',
		2	=> 'The field “%2$s” is too short, a minimum of %1$d characters is required.',
	),
	'FIELD_TOO_LONG'					=> array(
		1	=> 'The field “%2$s” is too long, a maximum of %1$d character is allowed.',
		2	=> 'The field “%2$s” is too long, a maximum of %1$d characters is allowed.',
	),
	'FIELD_TOO_SMALL'					=> 'The value of “%2$s” is too small, a minimum value of %1$d is required.',
	'FIELD_TOO_LARGE'					=> 'The value of “%2$s” is too large, a maximum value of %1$d is allowed.',
	'FIELD_INVALID_CHARS_INVALID'		=> 'The field “%s” has invalid characters.',
	'FIELD_INVALID_CHARS_NUMBERS_ONLY'	=> 'The field “%s” has invalid characters, only numbers are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_DOTS'	=> 'The field “%s” has invalid characters, only alphanumeric or . characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_ONLY'	=> 'The field “%s” has invalid characters, only alphanumeric characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_PUNCTUATION'	=> 'The field “%s” has invalid characters, only alphanumeric or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_ALPHA_SPACERS'	=> 'The field “%s” has invalid characters, only alphanumeric, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_UNDERSCORE'	=> 'The field “%s” has invalid characters, only alphanumeric or _ characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_DOTS'	=> 'The field “%s” has invalid characters, only letter, number or . characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_ONLY'	=> 'The field “%s” has invalid characters, only letter and number characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_PUNCTUATION'	=> 'The field “%s” has invalid characters, only letter, number or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_LETTER_NUM_SPACERS'		=> 'The field “%s” has invalid characters, only letter, number, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_UNDERSCORE'		=> 'The field “%s” has invalid characters, only letter, number or _ characters are allowed.',
	'FIELD_INVALID_DATE'				=> 'The field “%s” has an invalid date.',
	'FIELD_INVALID_URL'					=> 'The field “%s” has an invalid url.',
	'FIELD_INVALID_VALUE'				=> 'The field “%s” has an invalid value.',

	'FOE_MESSAGE'				=> 'Message from foe',
	'FOES_EXPLAIN'				=> 'Foes are users which will be ignored by default. Posts by these users will not be fully visible. Private messages from foes are still permitted. Please note that you cannot ignore moderators or administrators.',
	'FOES_UPDATED'				=> 'Your foes list has been updated successfully.',
	'FOLDER_ADDED'				=> 'Folder successfully added.',
	'FOLDER_MESSAGE_STATUS'		=> array(
		1	=> '%2$d out of %1$s stored',
		2	=> '%2$d out of %1$s stored',
	),
	'FOLDER_NAME_EMPTY'			=> 'You must enter a name for this folder.',
	'FOLDER_NAME_EXIST'			=> 'Folder <strong>%s</strong> already exists.',
	'FOLDER_OPTIONS'			=> 'Klasör seçenekleri',
	'FOLDER_RENAMED'			=> 'Klasör başarıyla yeniden adlandırıldı.',
	'FOLDER_REMOVED'			=> 'Klasör başarıyla kaldırıldı.',
	'FOLDER_STATUS_MSG'			=> array(
		1	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
		2	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
	),
	'FORWARD_PM'				=> 'ÖM ilet',
	'FORCE_PASSWORD_EXPLAIN'	=> 'Before you may continue browsing the board you are required to change your password.',
	'FRIEND_MESSAGE'			=> 'Message from friend',
	'FRIENDS'					=> 'Arkadaşlar',
	'FRIENDS_EXPLAIN'			=> 'Friends enable you quick access to members you communicate with frequently. If the template has relevant support any posts made by a friend may be highlighted.',
	'FRIENDS_OFFLINE'			=> 'Çevrimdışı',
	'FRIENDS_ONLINE'			=> 'Çevrimiçi',
	'FRIENDS_UPDATED'			=> 'Your friends list has been updated successfully.',
	'FULL_FOLDER_OPTION_CHANGED'=> 'The action to take when a folder is full has been changed successfully.',
	'FWD_ORIGINAL_MESSAGE'		=> '-------- Orjinal Mesaj --------',
	'FWD_SUBJECT'				=> 'Konu: %s',
	'FWD_DATE'					=> 'Zaman: %s',
	'FWD_FROM'					=> 'From: %s',
	'FWD_TO'					=> 'To: %s',

	'GLOBAL_ANNOUNCEMENT'		=> 'Genel duyuru',

	'GRAVATAR_AVATAR_EMAIL'			=> 'Gravatar eposta',
	'GRAVATAR_AVATAR_EMAIL_EXPLAIN'	=> 'Enter the email address you used for registering your account on <a href="http://www.gravatar.com/">Gravatar</a>.',
	'GRAVATAR_AVATAR_SIZE'			=> 'Avatar dimensions',
	'GRAVATAR_AVATAR_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',

	'HIDE_ONLINE'				=> 'Çevrimiçi durumumu gizle',
	'HIDE_ONLINE_EXPLAIN'		=> 'Changing this setting won’t become effective until your next visit to the board.',
	'HOLD_NEW_MESSAGES'			=> 'Do not accept new messages (New messages will be held back until enough space is available)',
	'HOLD_NEW_MESSAGES_SHORT'	=> 'New messages will be held back',

	'IF_FOLDER_FULL'			=> 'If folder is full',
	'IMPORTANT_NEWS'			=> 'Important announcements',
	'INVALID_USER_BIRTHDAY'			=> 'The entered birthday is not a valid date.',
	'INVALID_CHARS_USERNAME'	=> 'The username contains forbidden characters.',
	'INVALID_EMOJIS_USERNAME'	=> 'The username contains forbidden characters (Emoji).',
	'INVALID_CHARS_NEW_PASSWORD'=> 'The password does not contain the required characters.',
	'ITEMS_REQUIRED'			=> 'The items marked with * are required profile fields and need to be filled out.',

	'JOIN_SELECTED'				=> 'Join selected',

	'LANGUAGE'					=> 'Dil',
	'LINK_REMOTE_AVATAR'		=> 'Link off-site',
	'LINK_REMOTE_AVATAR_EXPLAIN'=> 'Enter the URL of the location containing the avatar image you wish to link to.',
	'LINK_REMOTE_SIZE'			=> 'Avatar dimensions',
	'LINK_REMOTE_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',
	'LOGIN_EXPLAIN_UCP'			=> 'Please login in order to access the User Control Panel.',
	'LOGIN_LINK'					=> 'Link or register your account on an external service with your board account',
	'LOGIN_LINK_EXPLAIN'			=> 'You have attempted to login with an external service that is not yet connected to an account on this board. You must now either link this account to an existing account or create a new account.',
	'LOGIN_LINK_MISSING_DATA'		=> 'Data that is necessary to link your account with an external service is not available. Please restart the login process.',
	'LOGIN_LINK_NO_DATA_PROVIDED'	=> 'No data has been provided to this page to link an external account to a forum account. Please contact the board administrator if you continue to experience problems.',
	'LOGIN_KEY'					=> 'Giriş anahtarı',
	'LOGIN_TIME'				=> 'Giriş zamanı',
	'LOGIN_REDIRECT'			=> 'You have been successfully logged in.',
	'LOGOUT_FAILED'				=> 'You were not logged out, as the request did not match your session. Please contact the board administrator if you continue to experience problems.',
	'LOGOUT_REDIRECT'			=> 'You have been successfully logged out.',

	'MARK_IMPORTANT'				=> 'Mark/Unmark as important',
	'MARKED_MESSAGE'				=> 'Marked message',
	'MAX_FOLDER_REACHED'			=> 'Maximum number of allowed user defined folders reached.',
	'MESSAGE_BY_AUTHOR'				=> 'by',
	'MESSAGE_COLOURS'				=> 'Message colours',
	'MESSAGE_DELETED'				=> 'Message successfully deleted.',
	'MESSAGE_EDITED'				=> 'Message successfully edited.',
	'MESSAGE_HISTORY'				=> 'Message history',
	'MESSAGE_REMOVED_FROM_OUTBOX'	=> 'This message was deleted by its author.',
	'MESSAGE_REPORTED_MESSAGE'		=> 'Reported message',
	'MESSAGE_SENT_ON'				=> 'on',
	'MESSAGE_STORED'				=> 'This message has been sent successfully.',
	'MESSAGE_TO'					=> 'To',
	'MESSAGES_DELETED'				=> 'Messages successfully deleted',
	'MOVE_DELETED_MESSAGES_TO'		=> 'Move messages from removed folder to',
	'MOVE_DOWN'						=> 'Aşağı taşı',
	'MOVE_MARKED_TO_FOLDER'			=> 'Move marked to %s',
	'MOVE_PM_ERROR'					=> array(
		1	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s was moved.',
		2	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s were moved.',
	),
	'MOVE_TO_FOLDER'				=> 'Klasöre taşı',
	'MOVE_UP'						=> 'Yukarı taşı',

	'NEW_FOLDER_NAME'				=> 'Yeni klasör adı',
	'NEW_PASSWORD'					=> 'Yeni şifre',
	'NEW_PASSWORD_CONFIRM_EMPTY'	=> 'Onay şifresini girmediniz.',
	'NEW_PASSWORD_ERROR'			=> 'Girdiğiniz şifreler eşleşmiyor.',

	'NOTIFICATIONS_MARK_ALL_READ'						=> 'Tüm bildirimleri okundu olarak işaretle',
	'NOTIFICATIONS_MARK_ALL_READ_CONFIRM'				=> 'Are you sure you want to mark all notifications read?',
	'NOTIFICATIONS_MARK_ALL_READ_SUCCESS'				=> 'All notifications have been marked read.',
	'NOTIFICATION_GROUP_MISCELLANEOUS'					=> 'Miscellaneous Notifications',
	'NOTIFICATION_GROUP_MODERATION'						=> 'Moderation Notifications',
	'NOTIFICATION_GROUP_ADMINISTRATION'					=> 'Administration Notifications',
	'NOTIFICATION_GROUP_POSTING'						=> 'Posting Notifications',
	'NOTIFICATION_METHOD_BOARD'							=> 'Bildirimler',
	'NOTIFICATION_METHOD_EMAIL'							=> 'Eposta',
	'NOTIFICATION_METHOD_JABBER'						=> 'Jabber',
	'NOTIFICATION_TYPE'									=> 'Bildirim türü',
	'NOTIFICATION_TYPE_BOOKMARK'						=> 'Someone replies to a topic you have bookmarked',
	'NOTIFICATION_TYPE_GROUP_REQUEST'					=> 'Someone requests to join a group you lead',
	'NOTIFICATION_TYPE_FORUM'							=> 'Someone replies to a topic in a forum to which you are subscribed',
	'NOTIFICATION_TYPE_IN_MODERATION_QUEUE'				=> 'A post or topic needs approval',
	'NOTIFICATION_TYPE_MODERATION_QUEUE'				=> 'Your topics/posts are approved or disapproved by a moderator',
	'NOTIFICATION_TYPE_PM'								=> 'Someone sends you a private message',
	'NOTIFICATION_TYPE_POST'							=> 'Someone replies to a topic to which you are subscribed',
	'NOTIFICATION_TYPE_QUOTE'							=> 'Someone quotes you in a post',
	'NOTIFICATION_TYPE_REPORT'							=> 'Someone reports a post',
	'NOTIFICATION_TYPE_REPORT_CLOSED'					=> 'Your report on a post is closed by a moderator',
	'NOTIFICATION_TYPE_REPORT_PM'						=> 'Someone reports a private message',
	'NOTIFICATION_TYPE_REPORT_PM_CLOSED'				=> 'Your report on a private message is closed by a moderator',
	'NOTIFICATION_TYPE_TOPIC'							=> 'Someone creates a topic in a forum to which you are subscribed',
	'NOTIFICATION_TYPE_ADMIN_ACTIVATE_USER'				=> 'User requiring activation',

	'NOTIFY_METHOD'					=> 'Bildirim yöntemi',
	'NOTIFY_METHOD_BOTH'			=> 'Both',
	'NOTIFY_METHOD_EMAIL'			=> 'Sadece eposta',
	'NOTIFY_METHOD_EXPLAIN'			=> 'Method for sending messages sent via this board.',
	'NOTIFY_METHOD_IM'				=> 'Jabber only',
	'NOTIFY_ON_PM'					=> 'Notify me on new private messages',
	'NOT_ADDED_FRIENDS_ANONYMOUS'	=> 'You cannot add the anonymous user to your friends list.',
	'NOT_ADDED_FRIENDS_BOTS'		=> 'You cannot add bots to your friends list.',
	'NOT_ADDED_FRIENDS_FOES'		=> 'You cannot add users to your friends list who are on your foes list.',
	'NOT_ADDED_FRIENDS_SELF'		=> 'You cannot add yourself to the friends list.',
	'NOT_ADDED_FOES_MOD_ADMIN'		=> 'You cannot add administrators and moderators to your foes list.',
	'NOT_ADDED_FOES_ANONYMOUS'		=> 'You cannot add the anonymous user to your foes list.',
	'NOT_ADDED_FOES_BOTS'			=> 'You cannot add bots to your foes list.',
	'NOT_ADDED_FOES_FRIENDS'		=> 'You cannot add users to your foes list who are on your friends list.',
	'NOT_ADDED_FOES_SELF'			=> 'You cannot add yourself to the foes list.',
	'NOT_AGREE'						=> 'I do not agree to these terms',
	'NOT_ENOUGH_SPACE_FOLDER'		=> 'The destination folder “%s” seems to be full. The requested action has not been taken.',
	'NOT_MOVED_MESSAGES'			=> array(
		1	=> 'You have %d private message currently on hold because of full folder.',
		2	=> 'You have %d private messages currently on hold because of full folder.',
	),
	'NO_ACTION_MODE'				=> 'No message action specified.',
	'NO_AUTHOR'						=> 'No author defined for this message',
	'NO_AVATAR'						=> 'No avatar selected',
	'NO_AVATAR_CATEGORY'			=> 'None',

	'NO_AUTH_DELETE_MESSAGE'		=> 'You are not authorised to delete private messages.',
	'NO_AUTH_EDIT_MESSAGE'			=> 'You are not authorised to edit private messages.',
	'NO_AUTH_FORWARD_MESSAGE'		=> 'You are not authorised to forward private messages.',
	'NO_AUTH_GROUP_MESSAGE'			=> 'You are not authorised to send private messages to groups.',
	'NO_AUTH_PROFILEINFO'			=> 'You are not authorised to change your profile information.',
	'NO_AUTH_READ_HOLD_MESSAGE'		=> 'You are not authorised to read private messages that are on hold.',
	'NO_AUTH_READ_MESSAGE'			=> 'You are not authorised to read private messages.',
	'NO_AUTH_PRINT_MESSAGE'			=> 'You are not authorised to print private messages.',
	'NO_AUTH_READ_REMOVED_MESSAGE'	=> 'You are not able to read this message because it was removed by the author.',
	'NO_AUTH_SEND_MESSAGE'			=> 'You are not authorised to send private messages.',
	'NO_AUTH_SIGNATURE'				=> 'You are not authorised to define a signature.',

	'NO_BCC_RECIPIENT'			=> 'Yok',
	'NO_BOOKMARKS'				=> 'Yer imleriniz bulunmuyor.',
	'NO_BOOKMARKS_SELECTED'		=> 'Hiçbir yer imi seçmediniz.',
	'NO_EDIT_READ_MESSAGE'		=> 'Private message cannot be edited because it has already been read.',
	'NO_EMAIL_USER'				=> 'The email/username information submitted could not be found.',
	'EMAIL_NOT_UNIQUE'			=> 'Email you specified is used by multiple users. You must specify username as well.',
	'NO_FOES'					=> 'No foes currently defined',
	'NO_FRIENDS'				=> 'No friends currently defined',
	'NO_FRIENDS_OFFLINE'		=> 'No friends offline',
	'NO_FRIENDS_ONLINE'			=> 'No friends online',
	'NO_GROUP_SELECTED'			=> 'No group specified.',
	'NO_IMPORTANT_NEWS'			=> 'No important announcements present.',
	'NO_MESSAGE'				=> 'Private message could not be found.',
	'NO_NEW_FOLDER_NAME'		=> 'You have to specify a new folder name.',
	'NO_NEWER_PM'				=> 'No newer messages.',
	'NO_OLDER_PM'				=> 'No older messages.',
	'NO_PASSWORD_SUPPLIED'		=> 'You cannot login without a password.',
	'NO_RECIPIENT'				=> 'No recipient defined.',
	'NO_RESET_TOKEN'			=> 'You did not provide a password reset token.',
	'NO_RULES_DEFINED'			=> 'No rules defined.',
	'NO_SAVED_DRAFTS'			=> 'No drafts saved.',
	'NO_TO_RECIPIENT'			=> 'None',
	'NO_WATCHED_FORUMS'			=> 'You are not subscribed to any forums.',
	'NO_WATCHED_SELECTED'		=> 'You have not selected any subscribed topics or forums.',
	'NO_WATCHED_TOPICS'			=> 'You are not subscribed to any topics.',

	'PASS_TYPE_ALPHA_EXPLAIN'	=> 'Password must be at least %1$s long, must contain letters in mixed case and must contain numbers.',
	'PASS_TYPE_ANY_EXPLAIN'		=> 'Must be at least %1$s long.',
	'PASS_TYPE_CASE_EXPLAIN'	=> 'Password must be at least %1$s long and must contain letters in mixed case.',
	'PASS_TYPE_SYMBOL_EXPLAIN'	=> 'Password must be at least %1$s long, must contain letters in mixed case, must contain numbers and must contain symbols.',
	'PASSWORD'					=> 'Şifre',
	'PASSWORD_ACTIVATED'		=> 'Yeni şifreniz aktifleştirildi.',
	'PASSWORD_RESET'			=> 'Şifreniz başarıyla sıfırlandı.',
	'PASSWORD_RESET_LINK_SENT'	=> 'If your account exists, a password reset link was sent to your registered email address. If you do not receive an email, it may be because you are banned, your account is not activated, you have requested multiple password resets within a short time frame, or you are not allowed to change your password. Contact an administrator if any of those reasons apply. Also, please check your spam filter.',
	'PERMISSIONS_RESTORED'		=> 'Orijinal izinler başarıyla geri yüklendi.',
	'PERMISSIONS_TRANSFERRED'	=> 'Successfully transferred permissions from <strong>%s</strong>, you are now able to browse the board with this user’s permissions.<br />Please note that admin permissions were not transferred. You are able to revert to your permission set at any time.',
	'PM_DISABLED'				=> 'Bu panoda özel mesajlaşma devre dışı bırakıldı.',
	'PM_FROM'					=> 'Gönderici',
	'PM_FROM_REMOVED_AUTHOR'	=> 'Bu mesaj artık kayıtlı olmayan bir kullanıcı tarafından gönderildi.',
	'PM_ICON'					=> 'ÖM ikon',
	'PM_INBOX'					=> 'Gelen',
	'PM_MARK_ALL_READ'			=> 'Tüm mesajları okundu olarak işaretle',
	'PM_MARK_ALL_READ_SUCCESS'	=> 'All private messages in this folder have been marked read',
	'PM_NO_USERS'				=> 'The requested users to be added do not exist.',
	'PM_OUTBOX'					=> 'Giden',
	'PM_SENTBOX'				=> 'Gönderilen mesajlar',
	'PM_SUBJECT'				=> 'Mesaj başlığı',
	'PM_TO'						=> 'Gönderilen',
	'PM_TOOLS'					=> 'Mesaj araçları',
	'PM_USERS_REMOVED_NO_PERMISSION'	=> 'Some users couldn’t be added as they do not have permission to read private messages.',
	'PM_USERS_REMOVED_NO_PM'	=> 'Some users couldn’t be added as they have disabled private message receipt.',
	'POST_EDIT_PM'				=> 'Mesajı düzenle',
	'POST_FORWARD_PM'			=> 'Mesajı ilet',
	'POST_NEW_PM'				=> 'Mesaj oluştur',
	'POST_PM_LOCKED'			=> 'Özel mesajlaşma kilitlendi.',
	'POST_PM_POST'				=> 'Mesajı alıntıla',
	'POST_QUOTE_PM'				=> 'Mesajı alıntıla',
	'POST_REPLY_PM'				=> 'Mesaja cevap yaz',
	'PRINT_PM'					=> 'Yazıcı görünümü',
	'PREFERENCES_UPDATED'		=> 'Tercihleriniz başarıyla güncellendi.',
	'PROFILE_INFO_NOTICE'		=> 'Bu bilgilerin diğer üyeler tarafından görüntülenebileceğini lütfen unutmayın. Kişisel bilgilerinizi eklerken dikkatli olun. * ile işaretlenmiş alanların doldurulması zorunludur.',
	'PROFILE_UPDATED'			=> 'Profiliniz başarıyla güncellendi.',
	'PROFILE_AUTOLOGIN_KEYS'	=> '"Beni Hatırla" girişleri panoyu ziyaret ettiğinizde otomatik olarak oturum açmanızı sağlar. Çıkış yaparsanız giriş anahtarı yalnızca çıkış yapmak için kullandığınız bilgisayarda silinir. Burada, bu siteye erişmek için kullandığınız diğer bilgisayarlarda oluşturulan giriş anahtarlarını görüntüleyebilirsiniz.',
	'PROFILE_NO_AUTOLOGIN_KEYS'	=> 'Kaydedilmiş "Beni hatırla" giriş anahtarı yok.',

	'RECIPIENT'							=> 'Alıcı',
	'RECIPIENTS'						=> 'Alıcılar',
	'REGISTRATION'						=> 'Kayıt',
	'OAUTH_REGISTRATION'				=> 'Harici hizmetleri kullanarak kayıt',
	'RELEASE_MESSAGES'					=> '%sBeklemedeki tüm mesajları serbest bırakın%s… Yeterli alan sağlanırsa bunlar uygun klasöre yeniden sıralanacaktır.',
	'REMOVE_ADDRESS'					=> 'Adresi kaldır',
	'REMOVE_SELECTED_BOOKMARKS'			=> 'Seçili yer imlerini kaldır',
	'REMOVE_SELECTED_BOOKMARKS_CONFIRM'	=> 'Seçili tüm yer imlerini silmek istediğinize emin misiniz?',
	'REMOVE_BOOKMARK_MARKED'			=> 'İşaretli yer imlerini kaldır',
	'REMOVE_FOLDER'						=> 'Klasörü kaldır',
	'REMOVE_FOLDER_CONFIRM'				=> 'Bu klasörü kaldırmak istediğinize emin misiniz?',
	'RENAME'							=> 'Yeniden adlandır',
	'RENAME_FOLDER'						=> 'Klasörü yeniden adlandır',
	'REPLIED_MESSAGE'					=> 'Mesaj cevaplandı',
	'REPLY_TO_ALL'						=> 'Gönderene ve tüm alıcılara cevap yaz',
	'REPORT_PM'							=> 'Özel mesajı raporla',
	'RESET_PASSWORD'					=> 'Şifreyi sıfırla',
	'RESET_TOKEN_EXPIRED_OR_INVALID'	=> 'Sağladığınız şifre sıfırlama belirteci geçersiz veya süresi dolmuş.',
	'RESIGN_SELECTED'					=> 'Resign selected',
	'RETURN_FOLDER'						=> '%1$sÖnceki klasöre dön%2$s',
	'RETURN_UCP'						=> '%sKullanıcı Kontrol Paneline dön%s',
	'RULE_ADDED'						=> 'Kural başarıyla eklendi.',
	'RULE_ALREADY_DEFINED'				=> 'Bu kural daha önce tanımlanmıştı.',
	'RULE_DELETED'						=> 'Kural başarıyla kaldırıldı.',
	'RULE_LIMIT_REACHED'				=> 'Daha fazla ÖM kuralı ekleyemezsiniz. Maksimum kural sayısına ulaştınız.',
	'RULE_NOT_DEFINED'					=> 'Kural doğru şekilde belirtilmedi.',
	'RULE_REMOVED_MESSAGES'				=> array(
		1	=> '%d özel mesaj, özel mesaj filtreleri nedeniyle kaldırıldı.',
		2	=> '%d özel mesaj, özel mesaj filtreleri nedeniyle kaldırıldı.',
	),

	'SAME_PASSWORD_ERROR'		=> 'Girdiğiniz yeni şifre mevcut şifrenizle aynıdır.',
	'SEARCH_YOUR_POSTS'			=> 'Mesajlarını görüntüle',
	'SENT_AT'					=> 'Gönderildi',			// Used before dates in private messages
	'SHOW_EMAIL'				=> 'Kullanıcılar benimle eposta yoluyla iletişime geçebilir',
	'SIGNATURE_EXPLAIN'			=> 'This is a block of text that can be added to posts you make. There is a %d character limit.',
	'SIGNATURE_PREVIEW'			=> 'Your signature will appear like this in posts',
	'SIGNATURE_TOO_LONG'		=> 'Your signature is too long.',
	'SELECT_CURRENT_TIME'		=> 'Geçerli saati seçin',
	'SELECT_TIMEZONE'			=> 'Zaman dilimi seç',
	'SORT'						=> 'Sort',
	'SORT_COMMENT'				=> 'File comment',
	'SORT_DOWNLOADS'			=> 'Downloads',
	'SORT_EXTENSION'			=> 'Extension',
	'SORT_FILENAME'				=> 'Dosya adı',
	'SORT_POST_TIME'			=> 'Post time',
	'SORT_SIZE'					=> 'Dosya boyutu',

	'TIMEZONE'					=> 'Zaman dilimi',
	'TIMEZONE_DATE_SUGGESTION'	=> 'Öneri: %s',
	'TIMEZONE_INVALID'			=> 'Seçtiğiniz saat dilimi geçersiz.',
	'TO'						=> 'Alıcı',
	'TO_MASS'					=> 'Alıcılar',
	'TO_ADD'					=> 'Alıcı ekle',
	'TO_ADD_MASS'				=> 'Alıcılar ekle',
	'TO_ADD_GROUPS'				=> 'Grupları ekle',
	'TOO_MANY_RECIPIENTS'		=> 'Çok fazla alıcıya özel mesaj göndermeye çalıştınız.',
	'TOO_MANY_REGISTERS'		=> 'Bu oturum için maksimum kayıt denemesi sayısını aştınız. Lütfen daha sonra tekrar deneyiniz.',

	'UCP'						=> 'Kullanıcı Kontrol Paneli',
	'UCP_ACTIVATE'				=> 'Hesabı aktifleştir',
	'UCP_ADMIN_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. The administrator will review your account and if approved you will receive an email at the address you specified.',
	'UCP_ATTACHMENTS'			=> 'Ekler',
	'UCP_AUTH_LINK'				=> 'External accounts',
	'UCP_AUTH_LINK_ASK'			=> 'You currently have no account associated with this external service. Click the button below to link your board account to an account with this external service.',
	'UCP_AUTH_LINK_ID'			=> 'Unique identifier',
	'UCP_AUTH_LINK_LINK'		=> 'Link',
	'UCP_AUTH_LINK_MANAGE'		=> 'Manage external account associations',
	'UCP_AUTH_LINK_NOT_SUPPORTED'	=> 'Linking board accounts to external services is not supported by this board’s current authentication method.',
	'UCP_AUTH_LINK_TITLE'		=> 'Manage your external account associations',
	'UCP_AUTH_LINK_UNLINK'		=> 'Unlink',
	'UCP_COPPA_BEFORE'			=> 'Before %s',
	'UCP_COPPA_ON_AFTER'		=> 'On or after %s',
	'UCP_EMAIL_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. You will receive an email at the address you provide that contains an account activation link.',
	'UCP_JABBER'				=> 'Jabber address',
	'UCP_LOGIN_LINK'			=> 'Set up an external account association',

	'UCP_MAIN'					=> 'Genel Bakış',
	'UCP_MAIN_ATTACHMENTS'		=> 'Ekleri yönet',
	'UCP_MAIN_BOOKMARKS'		=> 'Yer imlerini yönet',
	'UCP_MAIN_DRAFTS'			=> 'Taslakları yönet',
	'UCP_MAIN_FRONT'			=> 'Ön sayfa',
	'UCP_MAIN_SUBSCRIBED'		=> 'Abonelikleri Yönet',

	'UCP_NO_ATTACHMENTS'		=> 'Hiçbir dosya göndermediniz.',

	'UCP_NOTIFICATION_LIST'				=> 'Bildirimleri yönet',
	'UCP_NOTIFICATION_LIST_EXPLAIN'		=> 'Burada tüm geçmiş bildirimleri görüntüleyebilirsiniz.',
	'UCP_NOTIFICATION_OPTIONS'			=> 'Bildirim seçeneklerini düzenle',
	'UCP_NOTIFICATION_OPTIONS_EXPLAIN'	=> 'Burada pano için tercih ettiğiniz bildirim yöntemlerini ayarlayabilirsiniz.',

	'UCP_PREFS'					=> 'Pano tercihleri',
	'UCP_PREFS_PERSONAL'		=> 'Genel ayarları düzenle',
	'UCP_PREFS_POST'			=> 'Gönderim varsayılanlarını düzenle',
	'UCP_PREFS_VIEW'			=> 'Görüntüleme seçeneklerini düzenle',

	'UCP_PM'					=> 'Özel mesajlar',
	'UCP_PM_COMPOSE'			=> 'Mesaj oluştur',
	'UCP_PM_DRAFTS'				=> 'ÖM taslaklarını yönet',
	'UCP_PM_OPTIONS'			=> 'Kurallar, klasörler &amp; ayarlar',
	'UCP_PM_UNREAD'				=> 'Okunmamış mesajlar',
	'UCP_PM_VIEW'				=> 'Mesajı görüntüle',

	'UCP_PROFILE'				=> 'Profil',
	'UCP_PROFILE_AVATAR'		=> 'Avatarı düzenle',
	'UCP_PROFILE_PROFILE_INFO'	=> 'Profili düzenle',
	'UCP_PROFILE_REG_DETAILS'	=> 'Hesap ayarlarını düzenle',
	'UCP_PROFILE_SIGNATURE'		=> 'İmzayı düzenle',
	'UCP_PROFILE_AUTOLOGIN_KEYS'=> '“Beni hatırla” giriş anahtarlarını yönet',

	'UCP_USERGROUPS'			=> 'Kullanıcı grupları',
	'UCP_USERGROUPS_MEMBER'		=> 'Üyelikleri düzenle',
	'UCP_USERGROUPS_MANAGE'		=> 'Grupları yönet',

	'UCP_PASSWORD_RESET_DISABLED'	=> 'Şifre sıfırlama fonksiyonu devre dışı bırakıldı. Hesabınıza erişme konusunda yardıma ihtiyacınız varsa lütfen %sPano Yöneticisi%s ile iletişime geçin',
	'UCP_REGISTER_DISABLE'			=> 'Yeni bir hesap oluşturmak şu anda mümkün değil.',
	'UCP_RESEND'					=> 'Aktivasyon epostası gönder',
	'UCP_WELCOME'					=> 'Kullanıcı Kontrol Paneline hoş geldiniz. Buradan profilinizi, tercihlerinizi, abone olunan forum ve konuları izleyebilir, görüntüleyebilir ve güncelleyebilirsiniz. Ayrıca diğer kullanıcılara da mesaj gönderebilirsiniz (eğer izin veriliyorsa). Lütfen devam etmeden önce duyuruları okuduğunuza emin olun.',
	'UCP_ZEBRA'						=> 'Arkadaşlar &amp; Engelliler',
	'UCP_ZEBRA_FOES'				=> 'Engellileri yönet',
	'UCP_ZEBRA_FRIENDS'				=> 'Arkadaşları yönet',
	'UNDISCLOSED_RECIPIENT'			=> 'Gösterilmeyen alıcı',
	'UNKNOWN_FOLDER'				=> 'Bilinmeyen klasör',
	'UNWATCH_MARKED'				=> 'İşaretlileri takipten çık',
	'UPLOAD_AVATAR_FILE'			=> 'Makinenizden yükleyin',
	'UPLOAD_AVATAR_URL'				=> 'Bir URL üzerinden yükle',
	'UPLOAD_AVATAR_URL_EXPLAIN'		=> 'Enter the URL of the location containing the image. The image will be copied to this site.',
	'USERNAME_ALPHA_ONLY_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only alphanumeric characters.',
	'USERNAME_ALPHA_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use alphanumeric, space or -+_[] characters.',
	'USERNAME_ASCII_EXPLAIN'		=> 'Username must be between %1$s and %2$s long and use only ASCII characters, so no special symbols.',
	'USERNAME_LETTER_NUM_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only letter or number characters.',
	'USERNAME_LETTER_NUM_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use letter, number, space or -+_[] characters.',
	'USERNAME_CHARS_ANY_EXPLAIN'	=> 'Length must be between %1$s and %2$s.',
	'USERNAME_TAKEN_USERNAME'		=> 'The username you entered is already in use, please select an alternative.',
	'USERNAME_DISALLOWED_USERNAME'	=> 'The username you entered has been disallowed or contains a disallowed word. Please choose a different name.',
	'USER_NOT_FOUND_OR_INACTIVE'	=> 'The usernames you specified could either not be found or are not activated users.',

	'VIEW_AVATARS'				=> 'Avatarları görüntüle',
	'VIEW_EDIT'					=> 'Görüntüle/Düzenle',
	'VIEW_FLASH'				=> 'Flash animasyonlarını görüntüle',
	'VIEW_IMAGES'				=> 'Mesajlardaki resimleri görüntüle',
	'VIEW_NEXT_HISTORY'			=> 'Next PM in history',
	'VIEW_NEXT_PM'				=> 'Sonraki ÖM',
	'VIEW_PM'					=> 'Mesajı görüntüle',
	'VIEW_PM_INFO'				=> 'Mesaj ayrıntıları',
	'VIEW_PM_MESSAGES'			=> array(
		1	=> '%d mesaj',
		2	=> '%d mesaj',
	),
	'VIEW_PREVIOUS_HISTORY'		=> 'Geçmiş önceki ÖM',
	'VIEW_PREVIOUS_PM'			=> 'Önceki ÖM',
	'VIEW_PROFILE'				=> 'Profilleri görüntüle',
	'VIEW_SIGS'					=> 'İmzaları görüntüle',
	'VIEW_SMILIES'				=> 'İfadeleri resim olarak görüntüle',
	'VIEW_TOPICS_DAYS'			=> 'Önceki günlerin konularının görüntülenmesi',
	'VIEW_TOPICS_DIR'			=> 'Konu sıralama yönü görüntülenmesi',
	'VIEW_TOPICS_KEY'			=> 'Konu sıralamasını şuna göre görüntüle',
	'VIEW_POSTS_DAYS'			=> 'Önceki günlerin mesajlarının görüntülenmesi',
	'VIEW_POSTS_DIR'			=> 'Mesaj sıralama yönü görüntülenmesi',
	'VIEW_POSTS_KEY'			=> 'Mesaj sıralamasını şuna göre görüntüle',

	'WATCHED_EXPLAIN'			=> 'Aşağıda abone olduğunuz forumların ve konuların bir listesi bulunmaktadır. Her ikisinde de yeni gönderiler konusunda bilgilendirileceksiniz. Abonelikten çıkmak için forumu veya konuyu işaretleyin ve ardından <em>İşaretlileri takipten çık</em> düğmesine basın.',
	'WATCHED_FORUMS'			=> 'izlenen forumlar',
	'WATCHED_TOPICS'			=> 'İzlenen konular',
	'WRONG_ACTIVATION'			=> 'Belirttiğiniz aktivasyon anahtarı veritabanındaki hiçbir aktivasyon anahtarıyla eşleşmiyor.',

	'YOUR_DETAILS'				=> 'Faaliyetiniz',
	'YOUR_FOES'					=> 'Engellilerin',
	'YOUR_FOES_EXPLAIN'			=> 'Kullanıcı adlarını kaldırmak için bunları seçin ve göndere tıklayın.',
	'YOUR_FRIENDS'				=> 'Arkadaşların',
	'YOUR_FRIENDS_EXPLAIN'		=> 'Kullanıcı adlarını kaldırmak için bunları seçin ve göndere tıklayın.',
	'YOUR_WARNINGS'				=> 'Uyarı seviyeniz',

	'PM_ACTION' => array(
		'PLACE_INTO_FOLDER'	=> 'Klasöre yerleştir',
		'MARK_AS_READ'		=> 'Okundu olarak işaretle',
		'MARK_AS_IMPORTANT'	=> 'Mesajı işaretle',
		'DELETE_MESSAGE'	=> 'Mesajı sil',
	),
	'PM_CHECK' => array(
		'SUBJECT'	=> 'Konu',
		'SENDER'	=> 'Gönderen',
		'MESSAGE'	=> 'Mesaj',
		'STATUS'	=> 'Mesaj statüsü',
		'TO'		=> 'Gönderilen',
	),
	'PM_RULE' => array(
		'IS_LIKE'		=> 'gibiyse',
		'IS_NOT_LIKE'	=> 'gibi değilse',
		'IS'			=> 'şuysa',
		'IS_NOT'		=> 'şu değilse',
		'BEGINS_WITH'	=> 'şununla başlıyorsa',
		'ENDS_WITH'		=> 'şununla bitiyorsa',
		'IS_FRIEND'		=> 'arkadaş ise',
		'IS_FOE'		=> 'engellilerde ise',
		'IS_USER'		=> 'kullanıcı ise',
		'IS_GROUP'		=> 'şu kullanıcı grubunun içindeyse',
		'ANSWERED'		=> 'cevaplandıysa',
		'FORWARDED'		=> 'iletildiyse',
		'TO_GROUP'		=> 'benim varsayılan grubuma ise',
		'TO_ME'			=> 'banaysa',
	),

	'GROUPS_EXPLAIN'	=> 'Kullanıcı grupları pano yöneticilerinin kullanıcıları daha iyi yönetmesini sağlar. Varsayılan olarak belirli bir gruba yerleştirileceksiniz, bu varsayılan grubunuzdur. Bu grup diğer kullanıcılara nasıl görünebileceğinizi tanımlar, örneğin kullanıcı adınızın rengi, avatarınız, rütbeniz vb. Yöneticinin izin verip vermemesine bağlı olarak varsayılan grubunuzu değiştirmenize izin verilebilir. Ayrıca başka gruplara yerleştirilebilir veya katılmanıza izin verilebilir. Bazı gruplar içeriği görüntülemeniz veya diğer alanlardaki yeteneklerinizi artırmanız için size ek izinler verebilir.',
	'GROUP_LEADER'		=> 'Liderlikler',
	'GROUP_MEMBER'		=> 'Üyelikler',
	'GROUP_PENDING'		=> 'Bekleyen üyelikler',
	'GROUP_NONMEMBER'	=> 'Olunmayan üyelikler',
	'GROUP_DETAILS'		=> 'Grup ayrıntıları',

	'NO_LEADER'		=> 'Grup liderliği yok',
	'NO_MEMBER'		=> 'Grup üyeliği yok',
	'NO_PENDING'	=> 'Bekleyen üyelik yok',
	'NO_NONMEMBER'	=> 'Üyeliği olmayan gruplar yok',
));
